### ISSUE TITLE
Flameshot crashes when try to save the screenshot to file

### ISSUE THREAD

**Issue by javitoom** [lupoDharkael/flameshot#1]
Error printed: Cannot mix incompatible Qt library (version 0x50800) with this library (version 0x50900)

Operative system: Arch Linux x86_64

**Comment by lupoDharkael** [comment]
Ok I've found the problem. Due to a change in the mechanism of Flameshot used to be on top of the screen, the file dialog can't be shown. It's easy to solve, I'll have it done for tomorrow.

**Comment by chrunchyjesus** [comment]
I have the same issue on Manjaro KDE with both Flameshot v0.5.0-3 and the Git version. For some strange reason it works in my virtual machine with the same distro and DE.

**Comment by lupoDharkael** [comment]
@chrunchyjesus that's weird.
Could you tell the the exact process to reproduce?

**Comment by chrunchyjesus** [comment]
Install with `pacaur -S flameshot` and start the GUI for taking a screenshot with `flameshot gui`.

If there are any information you need to know please tell me.

**Comment by chrunchyjesus** [comment]
My issue got solved at #161 . Although I still do not know why `flameshot gui` crashes when trying to save a screenshot without having `flameshot` running first but does not in my virtual machine, I do not care about it anymore.

Sorry for the inconvenience.

**Comment by Xananax** [comment]
I fixed the problem by installing and running `dunst`. Indeed, if there's nothing to catch the notification, Flameshot was just hanging.

**Comment by adityathebe** [comment]
> I fixed the problem by installing and running `dunst`. Indeed, if there's nothing to catch the notification, Flameshot was just hanging.

Thank you ! Running dunst also fixed the problem for me. (Kernel: 5.4.15-arch1-1 )

**Comment by bluedaze** [comment]
> I fixed the problem by installing and running `dunst`. Indeed, if there's nothing to catch the notification, Flameshot was just hanging.

Just want to say that this also fixed my issue. Thanks!

**Comment by piotrek-k** [comment]
Hi, the issue is closed but problem still persists. I'm running flameshot v0.6.0 on Manjaro with i3 desktop environment. After taking screenshot, Flameshot freezes for some time, then silently crashes. Kinda frustrating, you cannot take more screenshots during freeze. Installing `dunst` helped. I propose checking if notification deamon is present before startup.

**Comment by 3rikk** [comment]
I still have the same issue on manjaro with KDE. Using dunst fixes it, but i prefer the default KDE notifications.

**Comment by amenat** [comment]
Yes. Installing `dunst` fixes this issue. But it should not be required right?
 
I agree with @piotrek-k , a check for presence of notification daemon is good idea.
