### ISSUE TITLE
It needs a desktop to init flameshot

### ISSUE THREAD

**Issue by simonbcn** [lupoDharkael/flameshot#10]
In https://github.com/lupoDharkael/flameshot#considerations you say:

> In order to speed up the first launch of Flameshot (DBus init of the app can be slow), consider starting the application automatically on boot.

But the only desktop created by installation is for capture with GUI. It would be necessary another desktop file like `flameshot-init.desktop`, for example, with `Exec=/usr/local/bin/flameshot`.

**Comment by lupoDharkael** [comment]
I actually use the built-in functionality provided by the desktop environment to launch the command `flameshot`.
I suppose having such ".desktop" file would be more consistent.

**Comment by simonbcn** [comment]
In Gnome it's necessary to create a `.desktop` file in order to execute a program at the beginning of the session.

**Comment by lupoDharkael** [comment]
I've added the flameshot-init.desktop file in the last commit. I'm closing the issue!
