### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Theprim0** [lupoDharkael/flameshot#106]
falta error appears while _qmake && make_ in debian

In file included from src/main.cpp:21:0:
./src/utils/confighandler.h:20:47: fatal error: src/capture/widgets/capturebutton.h: No existe el fichero o el directorio
 #include "src/capture/widgets/capturebutton.h"
                                               ^
compilation terminated.
Makefile:938: fallo en las instrucciones para el objetivo 'main.o'
make: *** [main.o] Error 2

**Comment by lupoDharkael** [comment]
I forgot to add the modified directories in the last commit. This will be fixed in  a few minutes.

**Comment by lupoDharkael** [comment]
Should be working now. Sorry for the inconvenience.
