### ISSUE TITLE
[Improvement] add a screenshot submenu item in the flameshot right-click menu

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#113]
suggest to add a screenshot submenu item in the flameshot right-click menu to facilitate Ubuntu users.
![image](https://user-images.githubusercontent.com/10769951/36133123-681915a4-10b6-11e8-928d-23fb6f3262b7.png)

**Comment by lupoDharkael** [comment]
seems reasonable.
I'll implement it.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/009b6fb71a5e4596025964b5b6b680612c0250d8
