### ISSUE TITLE
Coordinating flameshot release in official Debian repo (and Ubuntu)

### ISSUE THREAD

**Issue by hosiet** [lupoDharkael/flameshot#116]
Hi,

I just pushed flameshot into official Debian repository. You'll be able to track the package at https://tracker.debian.org/flameshot soon.

With Ubuntu's automatic package import from Debian, flameshot should also appear in Ubuntu 18.04 LTS later if nothing unexpected happens, we'll see.

Current version in Debian is a git snapshot on 2018-01-14. With Ubuntu 18.04 LTS a long-term release, I'm looking for a stable version of flameshot which can be used by a wider range of users. As a result, could you please consider preparing another release for flameshot recently? The date of Debian import freeze is 2018-03-01 and some preparations before that would be appreciated.

**Comment by lupoDharkael** [comment]
I'll try to release a new version before the end of the next week.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/releases/tag/v0.5.1
