### ISSUE TITLE
[ Improvement ] the autostart of flameshot

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#125]
When I check this directory `~/.config/autostart`, the flameshot desktop file is `Flameshot.desktop`, and its content is:
```
[Desktop Entry]
Icon=system-run
Exec=flameshot
Terminal=false

```
![image](https://user-images.githubusercontent.com/10769951/36538320-e829e0c6-180d-11e8-8694-f754245c8d9e.png)

The flameshot icon is wrong and the contents of the entire desktop file should be changed to:
```
[Desktop Entry]
Encoding=UTF-8
Name=flameshot
Icon=flameshot
Exec=flameshot
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true

```

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/5461b27f0ed308754f34ea37b30d9eaa18c85994
