### ISSUE TITLE
Don't hardcode the icon

### ISSUE THREAD

**Issue by now-im** [lupoDharkael/flameshot#126]
In linux we like to soup things up. We do customizations to our heart content. BUt if the icon is hardcoded it it hard for SVG icon themes to be applied. 
Here is the desktop file of flameshot:
```
[Desktop Entry]
Encoding=UTF-8
Name=Flameshot
Name=Take graphical screenshot
Name[es]=Tomar captura gráfica
GenericName[es]=Herramienta de captura de pantalla
Comment=Powerfull yet simple to use screenshot software.
Comment[es]=Potente pero simple de usar software de capturas.
Exec=/usr/bin/flameshot gui
TryExec=/usr/bin/flameshot
Icon=/usr/share/icons/flameshot.png
Terminal=false
Type=Application
Categories=Graphics
StartupNotify=false
```
If the icon is something like: `Icon=flameshot` it will be easy to theme. Then, I may able to add it in [la-capitaine-icon-theme](https://github.com/keeferrourke/la-capitaine-icon-theme)

**Comment by lupoDharkael** [comment]
Please, provide more information.

**Comment by lupoDharkael** [comment]
Already fixed https://github.com/lupoDharkael/flameshot/issues/91 :)
