### ISSUE TITLE
Flameshot Is not opening on Ubuntu 17.10

### ISSUE THREAD

**Issue by muzammilijaz** [lupoDharkael/flameshot#127]
Flameshot Is not opening on Ubuntu 17.10.Please fix it. Unable to capture screen

**Comment by lupoDharkael** [comment]
What desktop environment?
Does it work if you launch it from the tray icon?

**Comment by muzammilijaz** [comment]
Sir,
I am using Gnome 3.26.2 (Wayland) Ubuntu 17.10. After install flameshot i have tray icon when i click on tray icon its show this error "Unable to capture screen". Also configure flameshot is working fine. When i click on flameshot gui its show "Unable to capture screen" . Please find the attachements
Thanks
![screenshot from 2018-02-24 12-09-08](https://user-images.githubusercontent.com/21077175/36626833-b161758c-195b-11e8-8ce5-871cbe23112b.png)
![screenshot from 2018-02-24 12-05-46](https://user-images.githubusercontent.com/21077175/36626834-b19f5906-195b-11e8-9cff-e34f34436e8d.png)
![screenshot from 2018-02-24 12-04-06](https://user-images.githubusercontent.com/21077175/36626835-b1d9ce42-195b-11e8-8ec1-4c6e31a43574.png)

**Comment by lupoDharkael** [comment]
I'll test it on a virtual machine.

**Comment by hosiet** [comment]
I'm wondering if you are running flameshot under Wayland. That might be important.

**Comment by muzammilijaz** [comment]
I try Flameshot on **Xorg** Ubuntu 17.10,Flameshot working Fine.but Falmeshot not working on **Wayland**.

**Comment by muzammilijaz** [comment]
@lupoDharkael Thank you so much for creating awesome tool. Flameshot is 100% alternative to Lightshot for windows. Flameshot is easy to use.
