### ISSUE TITLE
Add distro name in the packages generated by Travis

### ISSUE THREAD

**Issue by lupoDharkael** [lupoDharkael/flameshot#129]
After a release I need to change the name of every package adding the name its target system. Packages should be named flameshot_{version}-{distro}-{arch}.{extension} as you can see here: https://github.com/lupoDharkael/flameshot/releases/tag/v0.5.1

This doesn't apply to the appimage package.

**Comment by ZetaoYang** [comment]
@lupoDharkael Ok, I will solve it soon.
