### ISSUE TITLE
Version number doesn't appear when "flameshot -v"

### ISSUE THREAD

**Issue by cmolinaord** [lupoDharkael/flameshot#13]
I'm currently using Flameshot under Archlinux with XFCE. I installed flameshot version 4.1 from the AUR repo.

The problem is when doing
`flameshot -v` or `flameshot --version`
doesn't appear the version number. (The QT version number actually appear)

Also, it doesn't appear in the graphic window "Information"

**Comment by lupoDharkael** [comment]
I need to investigate better ways to extract that information into the make process. It may not work with some packaging setups, probably.

**Comment by lupoDharkael** [comment]
fixed in https://github.com/lupoDharkael/flameshot/commit/c54d327d9ca692ddfdb981f18eb24476d64e5180
