### ISSUE TITLE
ESC does not close flameshot after alt+tab

### ISSUE THREAD

**Issue by glaubersm** [lupoDharkael/flameshot#133]
Hi
Thank you very much for your great software.
I use flameshot 0.5.1 on Arch Linux, KDE Plasma 5.12.2 and I just found a bug.

enable system tray icon
click flameshot icon in system tray
press alt+tab to try focus another window
press ESC to close flameshot
flameshot is still active

**Comment by lupoDharkael** [comment]
Flameshot looses the keyboard focus after Atl+tab in Plasma.
Thanks for the report

**Comment by greno4ka** [comment]
Yes, It's still reproducable on alt linux (sisyphus) cinnamon.

**Comment by glaubersm** [comment]
it's still reproducible with flameshot 0.8.

**Comment by borgmanJeremy** [comment]
I think the only way to handle this is to have flameshot quit when alt tab is pressed. Basically we treat alt-tab as esc.

**Comment by veracioux** [comment]
Does PR https://github.com/flameshot-org/flameshot/pull/1958 help with this?
