### ISSUE TITLE
Full screenshot over gui screenshot fail

### ISSUE THREAD

**Issue by OlivierMary** [lupoDharkael/flameshot#135]
Hi,

I'm on KDE/Plasma on Archlinux.

I have  map `CTRL+PRINT` with `flameshot gui -p ~/flameshot/captures`
and `PRINT` with `flameshot full -c -p ~/flameshot/captures`

If I take a gui screen `CTRL+PRINT` make a selection in my screen.
Stay with flameshot open.
Take over that a full screen `PRINT` at this point that block flameshot a time after that it's killed by KDE maybe I don't know. But for a while screen / flameshot is blocked.

Fullscreen is done by the way:
![2018-02-28-01 14 48](https://user-images.githubusercontent.com/4348675/36762656-fcfb4204-1c24-11e8-8afd-53ba661d20d9.png)

**Comment by lupoDharkael** [comment]
I can reproduce here. Thanks for the report.

**Comment by lupoDharkael** [comment]
It should be fixed here: https://github.com/lupoDharkael/flameshot/commit/fff5888152f1e7126b7bdfd7bc9124f544ff5816

**Comment by OlivierMary** [comment]
thanks for the fast patch @lupoDharkael
