### ISSUE TITLE
Tray icon is hardcoded

### ISSUE THREAD

**Issue by orange-buffalo** [lupoDharkael/flameshot#143]
Currently the tray icon of Flameshot is hardcoded (bil-elmoussaoui/Hardcode-Tray#506):
> The application uses an icon from the qresource file. Which means it's hardcoded on the binary file
https://github.com/lupoDharkael/flameshot/blob/b1174a1e0501fff9e1d09bdf14028ca230746fe5/src/core/controller.cpp#L128

This leads to inconsistent icons styling for those who are using solutions like [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) (please note that all icons are in common style, but Flameshot uses its own, theme-independent icon):

![image](https://user-images.githubusercontent.com/4532247/36868631-0b4af452-1ded-11e8-8d8b-684e51a873de.png)

This could be improved to allow theme-based icons to be used:
> You should report that upstream so they can use QIcon::fromTheme("flameshot-tray) and fall back to the hardcoded icon if nothing was found

@bil-elmoussaoui kindly suggested to provide a PR for this if Flameshot team is willing to accept it.

**Comment by ZetaoYang** [comment]
Have a try.
flameshot/src/core/controller.cpp:

```
m_trayIcon = new QSystemTrayIcon();
m_trayIcon->setToolTip("Flameshot");
m_trayIcon->setContextMenu(trayIconMenu);
QIcon trayicon = QIcon::fromTheme("flameshot-tray", QIcon(":img/flameshot.png"));
m_trayIcon->setIcon(trayicon);
```

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/dddd1853941ce4c152d8ed9b6e619258557e4db4

**Comment by orange-buffalo** [comment]
@lupoDharkael could you please advise when the version containing this improvement is planned for release?

**Comment by orange-buffalo** [comment]
@lupoDharkael thanks for this improvement, it looks beautiful with the Papirus icons now:

![image](https://user-images.githubusercontent.com/4532247/46252985-c8fd4900-c4b4-11e8-89ed-38827b863ac6.png)
