### ISSUE TITLE
No issue, just a big big thank you!

### ISSUE THREAD

**Issue by zell-mbc** [lupoDharkael/flameshot#144]
Didn't know where to leave this so I thought might as well report it here.
All I want to say is a big big thank you for developing Flameshot! I do lots of screenshots every day and in my 30 years in IT  I have not seen a tool which fits my needs and work-flow better than Flameshoot! Not on Windows and not on Linux!
1. Press key shortcut
2. Highlight section of interest (circle, arrow, ...)
3. Ctrl-C
4. Alt-Tab over to the app which needs the screen shot (email, Libre office)
5. Ctrl-V
Done! I just love it!

Now, if you want to improve the worlds best screen shot app even more I'd ask for the below:
- Add a possibility to hide the icons/options which are not of interest to a particular user. I for example, will never upload anything to Imgur, hiding this icon will make for an even cleaner UI
- In addition to arrow, circle, etc. add the option to add text. E.g. I sometimes want to show a flow in a screen shot and would use the line tool to hand draw numbers. Proper text would look more professional.
- The only issue I have is that the Flameshoot config UI is crashing when I try to access it. But this is a minor one for me and I saw you are on the case already anyway. If you need a tester pull me in. I am running KDE Neon on a Dell Laptop.

Thanks again for all the work you put into Flameshot!
Thomas

**Comment by lupoDharkael** [comment]
> Add a possibility to hide the icons/options which are not of interest to a particular user. I for example, will never upload anything to Imgur, hiding this icon will make for an even cleaner UI

Disabling tools is available in the configuration menu.

> In addition to arrow, circle, etc. add the option to add text. E.g. I sometimes want to show a flow in a screen shot and would use the line tool to hand draw numbers. Proper text would look more professional.

Text will be available in version 0.6.0

> The only issue I have is that the Flameshoot config UI is crashing when I try to access it. But this is a minor one for me and I saw you are on the case already anyway. If you need a tester pull me in. I am running KDE Neon on a Dell Laptop.

Did you compile it? Or installed the program using a package?


I'm glad you liked Flameshot!
