### ISSUE TITLE
question: How can acces to the app, after i disabled tray icon

### ISSUE THREAD

**Issue by Lvaskz** [lupoDharkael/flameshot#150]
Hi, i disabled the tray icon in the settings, but after that I can not enter to configure it again. I can not use  the app, how can reset it.
By the way I can not to set the app in spanish.

**Comment by ZetaoYang** [comment]
@Lvaskz edit or delete `~/.config/flameshot.ini`

**Comment by lupoDharkael** [comment]
You can use the .desktop file which starts the config menu.
![imagen](https://user-images.githubusercontent.com/14951430/36944932-d9d27822-1fa5-11e8-98be-8323e000ca0e.png)

**Comment by Lvaskz** [comment]
Hi, thanks for all your help, but nothing here help me, I do all that but nothing works
Some other thing?

**Comment by lupoDharkael** [comment]
Open your terminal and run `flameshot config --trayicon true`

**Comment by Lvaskz** [comment]
i did, but the terminal says command not found

**Comment by Lvaskz** [comment]
I have the appimage

**Comment by ZetaoYang** [comment]
@Lvaskz `./flameshot_x86_64_0.5.1.AppImage config --trayicon true`

**Comment by Lvaskz** [comment]
Thanks now is working. And my language in the system is in spanish but the application Still in English

**Comment by Lvaskz** [comment]
hi, thanks by your help i gonna close this issue, but i will open one about Spanish translate, to separate this things.
