### ISSUE TITLE
Flameshot crashes

### ISSUE THREAD

**Issue by chrunchyjesus** [lupoDharkael/flameshot#161]
Flameshot crashes when trying to save the screenshot or launching Flameshot Configuration.

[Journald for Flameshot GUI](https://user-images.githubusercontent.com/20382692/37057425-92f21b0e-2187-11e8-9d92-8a3f707531f4.png)
[Journald for Flameshot Config](https://user-images.githubusercontent.com/20382692/37057440-a01896e6-2187-11e8-81ac-0a484e5595d7.png)

Using Flameshot version 0.5.1-1 from the Community Repository of Manjaro Linux. Compiled with Qt version 5.10.1 if that helps.

**Comment by lupoDharkael** [comment]
There is a problem with the locales in your system. They are probably not configured properly.
Check this: https://stackoverflow.com/questions/19100708/mongodb-mongorestore-failure-localefacet-s-create-c-locale-name-not-valid

**Comment by chrunchyjesus** [comment]
That seems strange. They seem to be properly configured. Typing `locale` into my terminal returns
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
and I have two lines in my shell that explicit sets them. 
```
# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";
```
In KDE Settings every part of my system is set to use this locale too.

**Comment by hosiet** [comment]
I don't think that is a valid explanation.

Try the following snippet:

```bash
export LC_ALL=C
export LANG=C
flameshot
```

On my system, flameshot (version `0.5.1-3(Debian)`) will not crash.

**Comment by chrunchyjesus** [comment]
It works now by using the snippet from @hosiet as a startup script. Thanks! Here is what I have tried until my success:

* Directly launching the config crashes, regardless of whether using the .desktop file or in terminal.
* Directly launching `flameshot gui` crashes when trying to save a screenshot, regardless of whether using the .desktop file or in terminal.
* Launching the .desktop file of Flameshot leads to crashes when launching the config or trying to save a screenshot.
* Using a startup script to launch Flameshot (without the exports provided by @hosiet ) leads to crashes when launching the config or trying to save a screenshot.
* Launching Flameshot manually from terminal (without the snippet from @hosiet ) and launching the config or trying to save a screenshot works.

All these five listed methods produce consistent behaviour regardless of the locale I have set.

**Comment by chrunchyjesus** [comment]
I found out why Flameshot did not work the usual way for me. I have got two files `~/.config/plasma-localerc` and `~/.config/plasma-locale-settings.sh` setting the locale to `en_AT.UTF-8`. Changing them to `en_US.UTF-8` fixed it. Now I can use Flameshot even without exporting any shell variables first.

plasma-localerc content:
```
[Formats]
LANG=en_US.UTF-8
```

plasma-locale-settings.sh content:
```
export LANG=en_US.UTF-8
```

**Comment by VAggrippino** [comment]
Flameshot crashes for me as well. It happens whenever I try to save a screenshot or launch the configuration. At least for me, locales don't seem to be a factor.

All of my locales are set appropriately.

My `~/.config/plasma-localerc` is set correctly. I didn't have a `~/.config/plasma-locale-settings.sh` file, but I created one with just the `LANG` variable mentioned in the previous comment.

When I start flameshot from the terminal, it doesn't crash even if I don't set `LC_ALL=C` and `LANG=C` first. Those two variables are both set to `en_US.UTF-8`.

**Comment by holopanen** [comment]
Hi! I was using the Flatpak version on my Pop_OS! 20.10 and after set the correct langague settings described above it works fine.

if you use (or change to) the package version it works fine too.

**Comment by shenxiaojian** [comment]
I solved this problem by adding Notifications widget. You can use the following method to check if the same error as mine:
display system settings -> Notifications. If you find a warning says that `Could not find a Notification Widget which is required for display notifications`. Then you may have the same mistake as me. In this case, you just need to add Notifications widget to your panel. Everthing will be fun!
