### ISSUE TITLE
flameshot appimage is not translated to spanish

### ISSUE THREAD

**Issue by Lvaskz** [lupoDharkael/flameshot#163]
Hi, it suppose the flameshot appimage comes by default in spanish if my system have it, indeed  that is the regional language which i have, but the application continue in english. How can I configurate it? linuxmint 18.3 64 bit cinnamon desktop

**Comment by ZetaoYang** [comment]
@lupoDharkael I think it's better to add a language setting menu.

**Comment by Lvaskz** [comment]
So, that will be in the near future? If that is the case, language setting menu would be excellent.

**Comment by hosiet** [comment]
* Locale detection should work seamlessly; if not, consider it a bug.

* Language settings is a good feature but perhaps should only act as an override configuration on top of automatic detection.

**Comment by Lvaskz** [comment]
Well, it is a bug then.

**Comment by ZetaoYang** [comment]
I think this issue has been solved,

**Comment by Lvaskz** [comment]
Well, I am in ubuntu 18.04 now, I gonna close this, but while I used linuxmint 18.3, flameshot.appimage not set spanish.
