### ISSUE TITLE
Launching "take graphical screenshot" from unity dashboad doesnt wait for it to fade out

### ISSUE THREAD

**Issue by MarcoNicolodi** [lupoDharkael/flameshot#166]
Since flameshot launches instantly, it cant take a shot of the actual screen you intend to, intead it takes shot of the dashboard itself, since the unity dashboard hasnt fade out yet.

**Comment by Mondane** [comment]
If you have a multimonitor setup, you can workaround this by opening the dashboard on another monitor.

Another workaround would be to edit the desktop file /usr/share/applications/flameshot.desktop and change

```Exec=flameshot gui```

to 

```Exec=sh -c "sleep 1 && flameshot gui"```

**Comment by MarcoNicolodi** [comment]
Another workarround is pinning the program in the sidebar launcher.

But i think sleep 1 is the better way. Thanks.

**Comment by Mondane** [comment]
Note: Pinning only works if you keep the sidebar always visible.

**Comment by hosiet** [comment]
There is a known option provided by `flameshot` for capture delay: `flameshot gui -d <msec>` and I believe it is much better than invoking shell.
