### ISSUE TITLE
"Unable to write file" when exporting config

### ISSUE THREAD

**Issue by opennota** [lupoDharkael/flameshot#169]
I run `flameshot config`, go to the General tab, press Export. When there is already a file with the same name (the previously exported `flameshot.conf`), flameshot asks me if I want to overwrite it, and after I click "Yes", there's an error message: "Unable to write file".

BTW, I can't make a screenshot of the error dialog using flameshot: there's no reaction when I click the tray icon. When I close the dialog, it starts working again.

```
$ flameshot --version
Flameshot v0.5.1-14-g0523a83
Compiled with QT 5.6.2
```

**Comment by ZetaoYang** [comment]
@opennota Maybe need root permissions

**Comment by opennota** [comment]
@ZetaoYang Nope. I save to `~`.

**Comment by opennota** [comment]
Here's I think the relevant part of strace output:

```
access("/home/opennota/flameshot.conf", R_OK) = 0
access("/home/opennota/flameshot.conf", W_OK) = 0
access("/home/opennota/flameshot.conf", X_OK) = -1 EACCES (Permission denied)
```

**Comment by hosiet** [comment]
I can confirm this bug for flameshot in Debian (v0.5.1-3).

```
Run `flameshot config` with current user, go to the General tab, press Export. When there is already a file with the same name (the previously exported flameshot.conf), flameshot asks me if I want to overwrite it, and after I click "Yes", there's an error message: "Unable to write file".)
```

**Comment by hosiet** [comment]
https://github.com/lupoDharkael/flameshot/blob/0523a837223a0a14b4fce6999e581ba366bb1d98/src/config/geneneralconf.cpp#L99-L106 


<img width="702" alt="default" src="https://user-images.githubusercontent.com/8443926/37562662-1429ccf6-2aa9-11e8-96eb-6f93333e545a.png">

**Comment by opennota** [comment]
> Note that if a file with the name newName already exists, copy() returns false (i.e. QFile will not overwrite it).

https://doc.qt.io/qt-5/qfile.html#copy

**Comment by lupoDharkael** [comment]
Thanks for the report, this closes the issue:
https://github.com/lupoDharkael/flameshot/commit/0e81c6b1f9ffab8dc0cfff77429ebe7abf9b711d
