### ISSUE TITLE
KDE freezes when copying to clipboard

### ISSUE THREAD

**Issue by BeeHiveJava** [lupoDharkael/flameshot#170]
Hi!

First of all, great tool, enjoying using it. I have, however, noticed that KDE freezes for roughly 10-15 seconds after I copy to clipboard (that is: ```flameshot -c``` or ```flameshot gui``` (and then copy to clipboard option)). It does, however, NOT freeze when I upload to imgur, wait for the 'finished UI', and then select 'copy to clipboard'. I haven't looked into the code at all, but perhaps there's something different going on there? 

It's worth mentioning that it's not the entire desktop environment (e.g. I can still browse pages in chrome, chat in Discord, etc.) It's just the system UI (e.g. I can't open settings, open application launchers, switch applications, etc.).

I'd be more than happy to provide more information as needed!

### Flameshot version
```
Flameshot v0.5.1-15-g0e81c6b
Compiled with QT 5.10.1
```

### KDE
```
plasmashell 5.12.3
Qt: 5.10.1
KDE Frameworks: 5.44.0
kf5-config: 1.0
```

### OS + Kernel
 ```
4.14.27-1-MANJARO

LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.1.6
Codename:	Hakoila
```

**Comment by lupoDharkael** [comment]
I added a fix related to clipboard some weeks ago, it's weird it still happens in the most recent commit. I suppose I'll need to test it in a VM of your system. I use Fedora KDE and I don't experience any problems with the copy to clipboard.

**Comment by Bocchio** [comment]
Happens the same to me. Worked fine up until a week ago when I updated it.

**Comment by lupoDharkael** [comment]
I've been testing the commit and it freezes. I managed to solve this saving the file before it was copied to the clipboard: https://github.com/lupoDharkael/flameshot/commit/fff5888152f1e7126b7bdfd7bc9124f544ff5816
but now it freezes anyway. 
It looks like a bug somewhere in Plasma, I'll report it.

**Comment by lupoDharkael** [comment]
Here is the bug report: https://bugs.kde.org/show_bug.cgi?id=392897

**Comment by lupoDharkael** [comment]
The bug seems to be in QT itself, I've tried to mitigate it in Flameshot and now I don't experience any freezes. Please, test the master branch and confirm.

**Comment by Bocchio** [comment]
It works fine now! :smile:

**Comment by lupoDharkael** [comment]
Great! thanks for the report!

**Comment by Bocchio** [comment]
Thanks to you for this program, keep up the good work!

**Comment by BeeHiveJava** [comment]
Also confirmed for me, thanks for the effort. I dropped you some money in your PayPal, enjoy a beer on us!

**Comment by dginovker** [comment]
Still happening to me, Flameshot v0.6.0 with Qt 5.11.1. Running on Manjaro OS with KDE

**Comment by landaire** [comment]
Just wanted to say I'm encountering this issue as well.

```
$ flameshot -v
Flameshot v0.6.0
Compiled with Qt 5.12.0

$ plasmashell --version
plasmashell 5.14.5

$ uname -a
Linux larch 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux
```

**Comment by ShayBox** [comment]
Same issue, both on plasma and bspwm, could it be SDDM related?

**Comment by morpheusthewhite** [comment]
Same on bspwm (but not on Plasma)

**Comment by ShayBox** [comment]
Start dbus

**Comment by morpheusthewhite** [comment]
It is already running

**Comment by ShayBox** [comment]
Maybe you don't have a notification daemon running then, both of those
cause that

**Comment by morpheusthewhite** [comment]
Yes, I was missing a notification daemon. 

Thank you so much

**Comment by ripefig** [comment]
Same problem. Please reopen.

**Comment by y0sh1DE** [comment]
Same problem. please reopen.

**Comment by ripefig** [comment]
problem disappeared after logging out.

**Comment by slondr** [comment]
This bug resurfaced for me today

**Comment by westofer** [comment]
I had the bug too, I use bspwm
```
Flameshot v0.8.5
Compiled with Qt 5.15.1
```

**Comment by dginovker** [comment]
I found the cause of the issue (at least for me) - when no notification popup is installed, your DE freezes. I noticed Discord messages were freezing me too back when I had this issue.

**Comment by westofer** [comment]
@dginovker you are a legend! thanks. 
in arch linux I installed  `notification-daemon `. then 
```sh
mkdir $XDG_DATA_HOME/dbus-1/services/
echo '
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon-1.0/notification-daemon
' |  tee $XDG_DATA_HOME/dbus-1/services/org.freedesktop.Notifications.service
```

**Comment by dginovker** [comment]
@lupoDharkael not sure if you want to reopen with this newfound info ^

**Comment by borgmanJeremy** [comment]
I don't think this needs reopened as I do not want to maintain a "notification" build and a "non notification" build. However, I would happily merge a documentation update that helps others realized that a notification service (like dunst) is required.

**Comment by dginovker** [comment]
Would it be possible instead to check if a notification service exists, and if not, no notification is displayed?

I'd personally have loved that 🙏

**Comment by borgmanJeremy** [comment]
Im not sure there is a standard way to check for all the different notification managers.

**Comment by slondr** [comment]
> Im not sure there is a standard way to check for all the different notification managers.

Even if there was, I feel as though this issue should be handled within d-bus, not in client software — I know of a handful of programs now which experience the same crash for the same reason, and I think d-bus is ultimately to blame here

**Comment by borgmanJeremy** [comment]
Also every distro that is not DIY bundles a notification manager. I only experienced this issue as an arch user.

**Comment by westofer** [comment]
not a c dev but could it be async?

if the notification was something like `notify-send "copied to clipboard &" it wont block and freeze.

**Comment by landaire** [comment]
What do the properties of the `m_interface` look like here: https://github.com/flameshot-org/flameshot/blob/dfcc9cb96bf23b108b47f3c54f92b7a266603c5e/src/utils/systemnotification.cpp#L18-L23?

Should [`m_interface->isValid()`](https://doc.qt.io/qt-5/qdbusabstractinterface.html#isValid) be checked? To @westofer's point, `asyncCallWithArgumentList` could also be used here instead which may at least hide the issue: https://github.com/flameshot-org/flameshot/blob/dfcc9cb96bf23b108b47f3c54f92b7a266603c5e/src/utils/systemnotification.cpp#L65

**Comment by westofer** [comment]
sorry to ping but any update :D?

**Comment by slondr** [comment]
> not a c dev but could it be async?
> 
> if the notification was something like `notify-send "copied to clipboard " &` it wont block and freeze.

This isn't really how C works. A shell spawns processes for each call to a program like this – you _can_ replicate that behavior in C, but it's non-trivial and definitely not the best way to go about this

**Comment by westofer** [comment]
i meant the idea not spawning shell :sweat_smile: 
i guess I meant more like `async` in javascript, maybe flameshot shouldn't wait for the exit code of the notification demon?

**Comment by Kolyunya** [comment]
> Also every distro that is not DIY bundles a notification manager. I only experienced this issue as an arch user.

@borgmanJeremy I'm using Arch and had a very frustrating experience when the screenshot application would freeze for no reason. Had to dig inside the GitHub issues to find out that the notification manager was required. I think the application must check whether the manager is available or not or install some manager by default or at least to tell to install one at some point.

**Comment by slondr** [comment]
> Also every distro that is not DIY bundles a notification manager.

This seems like a poorly justified response for a program which does not have "sends notifications" as one of its primary purposes

**Comment by borgmanJeremy** [comment]
I know of no good solution to fix this issue without a major rework. If someone can come up with a good suggestion that does not add significant maintenance overhead I am open to hearing it. 

As a stop gap we can update the arch wiki so the notification / dbus requirements are much easier to find rather than digging through github.

**Comment by Kolyunya** [comment]
@borgmanJeremy is it like a system API which is being called? Something like `showNotification()`? Doesn't this API have a method like `canShowNotification()`? If not, that's a very poor API from my point of view, but we still work around this.

What do you think about showing a big alert window on the first application start which would let users know that the notification manager is absolutely required for the normal application functioning?

**Comment by borgmanJeremy** [comment]
We are using qtdbus to send a message to the notification service. When I'm at my computer I'll see if this works: https://doc.qt.io/qt-5/qdbusabstractinterface.html#isValid

**Comment by westofer** [comment]
what about @landaire solution https://github.com/flameshot-org/flameshot/issues/170#issuecomment-729491708

> asyncCallWithArgumentList could also be used here instead which may at least hide the issue:
instead of
> m_interface->callWithArgumentList( 

>

**Comment by borgmanJeremy** [comment]
isValid() will not work because the block happens before we can check if the object is valid. I'll consider switching to async but I want to think about the downstream consequences. As a stopgap I can change the timout to a couple of seconds instead of the default 25seconds.

**Comment by V0ldemrt** [comment]
I can confirm that this issue is soley because of the notifications and not flameshot-specific,
For example spotify and discord will freeze as well on an action which triggers a notification,

This issue is fixed by adding the notification widget in the panel/dock

**Comment by Kolyunya** [comment]
> I can confirm that this issue is soley because of the notifications and not flameshot-specific,
> For example spotify and discord will freeze as well on an action which triggers a notification,
> 
> This issue is fixed by adding the notification widget in the panel/dock

1. You can not say that a memory leak is not a bug because it's present in some other program.
2. Notification widgets are an optional module of the OS. The program *must not* malfunction, when this particular module is not installeded in the OS.

**Comment by V0ldemrt** [comment]
> > I can confirm that this issue is soley because of the notifications and not flameshot-specific,
> > For example spotify and discord will freeze as well on an action which triggers a notification,
> > This issue is fixed by adding the notification widget in the panel/dock
> 
> This assumes you're running a DE with a dock or panel and widgets like that. You may be, but many people do not.

But this is specific to KDE, and KDE is a Desktop environment and it has a panel by default

**Comment by Kolyunya** [comment]
> But this is specific to KDE, and KDE is a Desktop environment and it has a panel by default

@V0ldemrt it does have a panel but it does not have notifications system by default.

**Comment by borgmanJeremy** [comment]
You can also disable notifications from the config menu.

**Comment by mmahmoudian** [comment]
@Kolyunya 

> The application program must not malfunction, when this particular module is not installeded in the OS.

If the application is designed that way then it *can* require user to have notification daemon. Really that simple 😉

> Notification widgets are an optional module of the OS

You can not turn off the notification requirement in the Flameshot's config file. I hope it helps

> it does have a panel but it does not have notifications system by default.

The OP has mentioned that they use KDE Plasma, and KDE Plasma by default and by design do ship with panel and notification daemon.


To address the issue, other than the flag that was implemented in the config file to disable the notification, we have also added a part in documentation to clarify the issue and requirements:

https://flameshot.org/guide/troubleshooting/#linux

Please let me know if this concludes the issues for your setup

**Comment by V0ldemrt** [comment]
> > But this is specific to KDE, and KDE is a Desktop environment and it has a panel by default
> 
> @V0ldemrt it does have a panel but it does not have notifications system by default.

And thats what I said to enable notifications,

I didnt understand exactly, are you agreeing with me or disagreeing?

**Comment by slondr** [comment]
@V0ldemrt This issue (ie this GitHub Issue) is specific to kde. This issue (ie the actual problem) is not specific to kde.

**Comment by V0ldemrt** [comment]
Yes, but the root problem is fixed through my solution
Which is to enable notifications

The problem is not only in copying to clipboard, but other options like save as well
Whenever it tries to send notifications, if there is no daemon to handle notifications it will crash

**Comment by borgmanJeremy** [comment]
You can also disable flameshot notifications as I stated above.
