### ISSUE TITLE
 error: no matching function for call to ...captureFailed

### ISSUE THREAD

**Issue by Aquarian-Age** [lupoDharkael/flameshot#175]
/home/xuan/tools/flameshot/src/core/controller.cpp:78: error: no matching function for call to ‘Controller::connect(QPointer<CaptureWidget>&, void (CaptureWidget::*)(uint), Controller* const, void (Controller::*)(uint))’
                 this, &Controller::captureFailed);
我的qt编译器5.7 
请问这个该怎么做呢 谢谢
                                                 ^

**Comment by lupoDharkael** [comment]
Could you give some context about the problem?

**Comment by Aquarian-Age** [comment]
我使用openSUSE 42.3 gcc 4.7版本 昨天试着 rpmbuild -ab 发现提示GCC版本问题 今天早上重新编译了GCC4.9.4 晚上回去再试试 谢谢你的回复

**Comment by hosiet** [comment]
Providing full build log might be more helpful next time. Also please provide information in English so that everyone can understand.

**Comment by ZetaoYang** [comment]
@Aquarian-Age The version of GCC must be 4.9+.

**Comment by Aquarian-Age** [comment]
@ZetaoYang 谢谢 我升级了编译器的版本到4.9.4编译通过了
@lupoDharkael 已经编译好了 谢谢

**Comment by ZetaoYang** [comment]
@Aquarian-Age I think this issue could be closed.
