### ISSUE TITLE
Add option to configure auto startup on command line tool (flameshot config)

### ISSUE THREAD

**Issue by jvsell** [lupoDharkael/flameshot#176]
Currently we have just this options:
  -f, --filename <pattern>          Set the filename pattern
  -t, --trayicon <bool>             Enable or disable the trayicon
  -s, --showhelp <bool>             Show the help message in the capture mode
  -m, --maincolor <color-code>      Define the main UI color
  -k, --contrastcolor <color-code>  Define the contrast UI color
  -h, --help                        Displays this help

A good option is to configure the startup if is true or false, similar to --trayicon option.

**Comment by lupoDharkael** [comment]
Seems reasonable!

**Comment by lupoDharkael** [comment]
done! https://github.com/lupoDharkael/flameshot/commit/344d3275285f7b3ba11283d23d5cd7af55e81308
