### ISSUE TITLE
"Show the dimensions of the select" isn't working

### ISSUE THREAD

**Issue by CurtisBelt** [lupoDharkael/flameshot#177]
Clicking on the "Show the dimensions of the select" button doesn't do anything for me - no text shows up anywhere. I've actually never seen it work before, but recently have been needing that sort of functionality so I thought I would stop being lazy and submit the bug.

![image](https://user-images.githubusercontent.com/4251760/38120420-5393ca2a-338e-11e8-8974-972af18f22ca.png)

Installed flameshot via AUR https://www.archlinux.org/packages/community/x86_64/flameshot/
Have latest package version 0.5.1-1

**System Info**

* Antergos
* Gnome 3.28.0
* X11
* GeForce GTX 1080 Ti
* Proprietary Nvidia drivers
* Have 4 screens in a 2x2 arrangement, 2560x1080 each.

**Comment by hosiet** [comment]
Oh well... in your screenshot, I thought the arrow points at exactly the dimension information: 501 x 245. The information is shown inside that button and clicking it has no effect by design.

**Comment by CurtisBelt** [comment]
This is hilarious. From day 1 I perceived that to be an icon of random numbers, just representing the statistical nature or it something ... thanks ...closing lol
