### ISSUE TITLE
It doesn't show the tray icon on Gnome 3.26

### ISSUE THREAD

**Issue by simonbcn** [lupoDharkael/flameshot#18]
```
Arch Linux
GNOME Shell 3.26.1 on X
TopIcons Plus v21 (installed from git)
```

When I start Gnome session, flameshot starts but it doesn't show the tray icon.

**Comment by lupoDharkael** [comment]
Does it happen only with the session start? or always?

**Comment by simonbcn** [comment]
Only with the session start

**Comment by lupoDharkael** [comment]
I think this problem is out of the scope of this project. The are several problems with systray icons across desktop environments.
See:
https://github.com/phocean/TopIcons-plus/issues/91
https://github.com/awesomeWM/awesome/issues/1720

I wish I could help with this.

**Comment by simonbcn** [comment]
The problem is that now Gnome-shell ignores `X-GNOME-Autostart-Delay` entry in desktop file.

I like Gnome-Shell but with every version they break a lot of things. And Wayland is still unusable (_for me_). I'm thinking of switching to another desktop environment that is more user-friendly.

**Comment by simonbcn** [comment]
I've solved this changing the .desktop init file to execute this script:
```
#!/bin/env sh
sleep 5
exec /usr/bin/flameshot
```

**Comment by AlexWayfer** [comment]
> The problem is that now Gnome-shell ignores X-GNOME-Autostart-Delay entry in desktop file.

Any links to commit/bug/issue/thread?
