### ISSUE TITLE
Unusable with Gnome shell, and a datetime added to the default name would be awesome!

### ISSUE THREAD

**Issue by kramer65** [lupoDharkael/flameshot#181]
I've been trying to use flameshot in Ubuntu 18.04 which uses Gnome shell. I always open programs by hitting the super-button and then typing the name of the program. When I do that with flameshot however, it often still shows the gnome shell when I want to select the area. I created a gif of that behaviour below.

Furthermore. It is highly annoying that I always have to think of a name, because the default is "screenshot.png". It would be so much easier if the default would include a datetime (something like `2018-04-09 18:30:23 screenshot.png`). That would save me the hassle of thinking of a name for it. It may seem like a small thing, but when you're making screenshots 20 times a day this one is really a mind saver.

![ezgif-2-84bbcfd06a](https://user-images.githubusercontent.com/596581/38502770-8eb1eed6-3c10-11e8-8d95-790ed7849a48.gif)

**Comment by hosiet** [comment]
I believe the first problem is already fixed in upstream Debian as well as upstream here. Please contact Ubuntu developers to import new version into Ubuntu before it's too late (a.k.a. the final release of Ubuntu 18.04 LTS).

The second problem can be configured in the config window. Please examine current settings for it on your desktop.

**Comment by lupoDharkael** [comment]
While it can be configured I agree another default for the naming is more convenient so the user doesn't have to modify the configuration in order to save the capture without renaming it.

**Comment by kramer65** [comment]
I came back here because I just found the config myself. This is quite handy indeed, but a different default would be even better. Good software works out of the box.. :-)

And also good to hear that the Gnome shell issue has been solved. I just checked and I've got version `0.5.1-2` running on Ubuntu 18.04. If Canonical needs to update that I'd love to contact them, but I have no idea where and how. If you could give me a tip I'm happy to pass on the message.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/ab207d8546a772b7aa9a6bed641794f8b8d7c1ca

**Comment by hosiet** [comment]
@kramer65 You might need to contact Ubuntu's team that maintains `universe` packages or any certain Ubuntu Developers. Sorry I don't know more information about it.
