### ISSUE TITLE
Any chance of translating hardcoded SystemNotification title string?

### ISSUE THREAD

**Issue by hosiet** [lupoDharkael/flameshot#183]
https://github.com/lupoDharkael/flameshot/blob/7977b5a6a7e32c77644629716713ed25f20528ee/src/utils/systemnotification.h#L28-L32

I'm wondering if the string "Flameshot Info" could be marked as translatable. That might need some minor refactoring.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/1047aa0058eb1e8250b13e4415a3aeabcbdee0ee

**Comment by hosiet** [comment]
Looks great.
