### ISSUE TITLE
Quick key and/or start from top bar icon

### ISSUE THREAD

**Issue by kramer65** [lupoDharkael/flameshot#185]
Since I make screenshots more then 10 times per day I want a quick way to start it. With monosnap (which I used until recently on my mac) I could open it from the icon in the top bar. In flameshot I currently only see  Configuration, Information and Quit.

Would it be possible to have an item in there which says "Take screenshot" with a quick key defined behind it. So that it says for example: "take screenshot (ctrl+Alt+5)"

This would really make it a breeze to use.. :-)

**Comment by lupoDharkael** [comment]
I've added the menu item closing #113.
About the shortcut, I don't think it's a good idea to define them in Flameshot, here's why:
- It's common to have a preconfigured shortcut for screenshots in a freshly installed system, and most of times that means they will have priority over app defined shortcuts in runtime.
- 2 apps can't share the same shortcut, if another program registers the same shortcut as Flameshot first, Flameshot will fail to register it. (I've seen issues in other screenshot projects about this and it's awful)
- You can configure your own shortcuts very easily with the keyboard configuration of your desktop environment.

Configuring the shortcuts works different on every windows manager/desktop environment so it's hard for a program to define them like that.
But you as an user can define a shortcuts, there are tutorials and it's pretty easy.

I'm closing the issue, if you have questions, do not hesitate to ask them.
