### ISSUE TITLE
Feature request: possibility to add text to the image

### ISSUE THREAD

**Issue by kramer65** [lupoDharkael/flameshot#192]
I often create screenshots to make something clear to someone far away. I do that with arrows, highlights and also with text. Therefore it would be awesome if Flameshot would include a text option to write some words on it.

**Comment by lupoDharkael** [comment]
The tool is finally in development.
You can track the issue here:
https://github.com/lupoDharkael/flameshot/issues/11

**Comment by kramer65** [comment]
Ah, awesome to see that it's in the works. Keep up the good work. We love flameshot!

**Comment by jlyle** [comment]
I really love flameshot, it is my default screen grab utility now.  It would be nice if we could save the screenshot to a custom name/path.  If that's possible now, thanks!  if not, and you can add that functionality, thanks again!
