### ISSUE TITLE
Suggestion to replace ":" with "-" in time placeholder

### ISSUE THREAD

**Issue by orschiro** [lupoDharkael/flameshot#196]
I looked at comparable applications such as GNOME Screenshot and they use a `-` instead of `:` in the time placeholder. 

I suggest following this standard because dashes are safer to use in file names than colons, correct?

![flameshot time](https://user-images.githubusercontent.com/170947/39085701-c7754fc2-4586-11e8-841f-bcb1e605773f.png)

**Comment by Rmano** [comment]
I support this; the `:` character is illegal for VFAT or NTFS filesystems, and that can create really strange problem sharing screenshots.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/17ac6f7a352f136b7470b66f536d372861fc6d8d

**Comment by orschiro** [comment]
@lupoDharkael I am running the latest commit that included the text tool but I still cannot see this change being included. See below. Any ideas? Thanks!

![image](https://user-images.githubusercontent.com/170947/39956441-af021c58-55e0-11e8-9a1c-9064cc2c23b3.png)

**Comment by lupoDharkael** [comment]
because you are running an old binary.

**Comment by orschiro** [comment]
What do you mean by old binary? I am running the latest commit (rpm built) available as per https://travis-ci.org/lupoDharkael/flameshot.

**Comment by lupoDharkael** [comment]
The package from travis compiles the last commit, and the actual version has the problem fixed. How did you install the previous version?
