### ISSUE TITLE
[Suggestion] Support "Paste images as topmost floating windows" 

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#20]
Paste images as topmost floating windows like this https://www.snipaste.com

**Comment by lupoDharkael** [comment]
There are a bunch of interesting concepts in that software.
I'd like to check what could I get out of it (respecting the essence of Flameshot).
Thanks for the suggestion!

**Comment by lupoDharkael** [comment]
Here is a initial version of the tool, it will be improved in the future.
https://github.com/lupoDharkael/flameshot/commit/205cd7c87bfb984cc98f45e50dd8289ea7de5c54
