### ISSUE TITLE
Save to default directory

### ISSUE THREAD

**Issue by reitzig** [lupoDharkael/flameshot#204]
Please add an option to configure a default target directory where Flameshot will save to without opening the file chooser dialog.

**Comment by reitzig** [comment]
Oh! In another issue I stumbled over the  `-p` option. This is quite enough for me (since I manually configure the shortcut to take a screenshot anyway). While GUI config may be useful, my request changes to: please document all options in `--help`.

**Comment by lupoDharkael** [comment]
There is an example in the Readme and you can find it in the --help, help doesn't show every option doing `flameshot -h` because the help is contextual based on the first argument, you need to do `flameshot gui -h` to get a more specific information.
