### ISSUE TITLE
Upload to Imgur Error! 

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#21]
Upload to Imgur error.
![image](https://user-images.githubusercontent.com/10769951/33132582-f9169072-cfd4-11e7-8809-c3c8ec045fee.png)

**Comment by lupoDharkael** [comment]
Is it a persistent error? can you reproduce it everytime of just eventually?

**Comment by ZetaoYang** [comment]
@lupoDharkael  yes, it occured when i click that upload button everytime.

**Comment by lupoDharkael** [comment]
That's weird. It's working in my system and the server isn't throwing a descriptive error.
Looks like a problem specific to your system. What's your OS (specific version)?
I could try to reproduce the error and see what happens.

**Comment by ZetaoYang** [comment]
@lupoDharkael Oh,that is my network error. sorry
