### ISSUE TITLE
Travis error notification

### ISSUE THREAD

**Issue by lupoDharkael** [lupoDharkael/flameshot#213]
**Describe the bug**
The RPM build fails in travis and it isn't notified as a failed build.
```
PM build errors:
    Macro expanded in comment on line 59: %{name}.svg
    Macro expanded in comment on line 60: %{name}.svg
    File not found: /build/BUILDROOT/flameshot-0.5.1-1.fc27.x86_64/usr/share/applications/flameshot-init.desktop
    File not found: /build/BUILDROOT/flameshot-0.5.1-1.fc27.x86_64/usr/share/applications/flameshot-config.desktop
```
**Expected behavior**
A notification from Travis about a failed build.

**Comment by ZetaoYang** [comment]
@lupoDharkael PR[#214](https://github.com/lupoDharkael/flameshot/pull/214). But it isn't notified as a failed build. I'm trying to fix that problem.
