### ISSUE TITLE
Not remaining in memory when '_tray icon_' and '_start at init_' options are disabled

### ISSUE THREAD

**Issue by simonbcn** [lupoDharkael/flameshot#215]
`GNOME Shell 3.28.1 on Wayland`

### Explanation
I have associated `PrintScreen` key to invoke flameshot and make a capture: `flameshot gui`
I have disabled the flameshot options '_start at init_' and '_tray icon_' by 2 reasons: https://github.com/lupoDharkael/flameshot/issues/18 and because I think it is not necessary to have this program in memory for sporadic use of it (_taking screenshots in my case is not a continuous need_).
But this program remains resident in memory after the first call. Why? Is it really necessary if I don't use the tray icon nor 'start at init'?

### Conclusion
IMHO this program shouldn't remain in memory when '_tray icon_' and '_start at init_' options are disabled.

**Comment by lupoDharkael** [comment]
Please read this for an explanation about why Flameshot needs to be running in the background:
https://doc.qt.io/qt-5/qclipboard.html#notes-for-x11-users

**Comment by simonbcn** [comment]
I suppose the link you are referring to refers to the fact that the program needs to be kept in memory to use the clipboard. I'm talking about GNOME on Wayland, without X11. Moreover I don't see any option in flameshot to use the clipboard.

**Comment by lupoDharkael** [comment]
Flameshot still requires X11 on Wayland because it runs under XWayland. And yes Flameshot allows you to copy to the clipboard, in fact a lot of users use that feature very extensively. If you don't keep the process running you are unable to paste the contents of the clipboard.
Memory is cheap today and Flameshot uses just a few MB and most of the time it doesn't consume CPU.

**Comment by SleeplessSloth** [comment]
But if I already use a clipboard manager, isn't that redundant? An option to disable running in the background would be awesome to have
