### ISSUE TITLE
Help on configuration of tool

### ISSUE THREAD

**Issue by lucgiffon** [lupoDharkael/flameshot#216]
I know I can use right click for color and mouse for  thickness but I needed to read the documentation in order to discover how to do so. 

I think it would be nice to add something in the gui to explain briefly to the user how to configure the tools. 

I thought of something as simple as adding a "(right click to pick color, wheel up/down to select thickness)" string to the end of the hovering labels of the tools. Or maybe a "question-mark-icon" on which clicking would pop a help window?

What do you think?

**Comment by hosiet** [comment]
You must have overlooked the text that pops up every time the screenshot mode is triggered. I believe that text provides all information needed.

**Comment by lucgiffon** [comment]
Sorry
