### ISSUE TITLE
flameshot doesn't print its version number

### ISSUE THREAD

**Issue by sixpointzero** [lupoDharkael/flameshot#218]
**Describe the bug**
flameshot doesn't print its version number when using ``$ flameshot --version``

**To Reproduce**
```
$ flameshot --version
Flameshot 
Compiled with QT 5.10.1
```

**Expected behavior**
```
$ flameshot --version
Flameshot 0.5.1
Compiled with QT 5.10.1
```

**Desktop (please complete the following information):**
 - Arch Linux 4.14.40
 - 0.5.1

**Comment by lupoDharkael** [comment]
that happens because the binary was compiled without git installed. In future releases a compilation without git will have a less specific (hardcoded) version number. If you compile flameshot with git installed you get a version number if it is a release and a version+commit otherwise.
