### ISSUE TITLE
flameshot is not runnig in ubuntu 18.04

### ISSUE THREAD

**Issue by Lvaskz** [lupoDharkael/flameshot#223]
**Describe the bug**
The flameshot is not running in Ubuntu 18.04
Icon not appear in dock, no fuctions, nothing at all

**To Reproduce**
Download flameshot.appimage.
Right click, go permission, check make exexutable.
doble click flameshot.appimage

**Expected behavior**
Icon must to appear in dock ubuntu 18.04, and the app must running normal.

**Desktop **
 - OS: [ Ubuntu 18.04 Gnome]
 - Version [3.28]

**Comment by ningacoding** [comment]
Installing as documented [here](https://github.com/lupoDharkael/flameshot#installation)
with `apt install flameshot`, works extremely good.
![image](https://user-images.githubusercontent.com/17342546/40147331-e50e636e-592e-11e8-910c-28b1861d5bd4.png)

**Comment by Lvaskz** [comment]
Thanks for suggest. I will proof but actually I prefer a more agnostic solution. The use of debs packages generates some distrust to me. I think you could provide a flatpak package in the future, the updates arrive in real time, they are loaded in flathub or anywhere else you want, you could provide a flatpakref. And it could be better integrated into the desktop.

**Comment by Lvaskz** [comment]
Hi, it works really great. Are you thinking provide a snap? It would be nice, I see some advance in the main page. Will you?

**Comment by hosiet** [comment]
The problem is not related to Ubuntu 18.04. In fact, I could confirm that current AppImage binary downloaded from the Release page cannot run under my Debian Unstable. Terminal output is:

```
% ./flameshot_x86_64_0.5.1.AppImage 
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 274, resource id: 73400325, major code: 55 (CreateGC), minor code: 0
QXcbConnection: XCB error: 9 (BadDrawable), sequence: 275, resource id: 73400325, major code: 130 (Unknown), minor code: 
```

Not sure if it is to be fixed or not but the issue do exist.

**Comment by omkarnathsingh** [comment]
Please release a update for Ubuntu package, it was last updated in February.

**Comment by ZetaoYang** [comment]
@omkarnathsingh You can try Travis CI daily build version.

**Comment by omkarnathsingh** [comment]
@ZetaoYang Where to download those .deb file?

**Comment by ZetaoYang** [comment]
@omkarnathsingh  https://travis-ci.org/lupoDharkael/flameshot
![image](https://user-images.githubusercontent.com/10769951/40570932-c8cdf7c8-60c2-11e8-907a-f4ffcd569e02.png)

**Comment by omkarnathsingh** [comment]
Thanks. :)

**Comment by omkarnathsingh** [comment]
That link doesnt give anything to download, i checked multiple time

**Comment by ZetaoYang** [comment]
@omkarnathsingh Are you kidding me? 
![image](https://user-images.githubusercontent.com/10769951/40584137-b5d71b4c-61ce-11e8-841a-2bcc53424791.png)

**Comment by omkarnathsingh** [comment]
Not kidding. Maybe my ISP to blame then, that website shows me nothing, Firefox says website not found. Let me try using VPN.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by TragicWarrior** [comment]
@omkarnathsingh , you the link provided above is not the link that you would use.  You need to go to Travis CI and run the build for your system Xenial, Fedora, whatever...  After you do that, there will be a button that says "Raw Log".  Click on that and scroll to the bottom and look for a URL that has transfer.sh in it.

**Comment by TragicWarrior** [comment]
All, I have tried the Travis CI build on 18.04.  Since there is no BionicBeaver option I'm building for Xenial... I get the same problem.  Flameshot does not start.

**Comment by omkarnathsingh** [comment]
Developer please make a release, its not that easy to do all that to update, i am still on february version.

**Comment by ZetaoYang** [comment]
@omkarnathsingh Working in new docker building enviroment.
![image](https://user-images.githubusercontent.com/10769951/43933640-66e33c98-9c7d-11e8-90af-dbe5d6ff54a6.png)

**Comment by ZetaoYang** [comment]
@omkarnathsingh @TragicWarrior 
![image](https://user-images.githubusercontent.com/10769951/43936919-821ca642-9c8d-11e8-84a5-58e3850ccca5.png)

**Comment by TragicWarrior** [comment]
@ZetaoYang (face-palm)... not sure how I missed that.  ty!

@lupoDharkael , would still be nice to have an official release for Bionic.

**Comment by TragicWarrior** [comment]
@ZetaoYang , that's docker not Travis CI...  hmmm.  I hate to ask, but I'm a LXC guy.  how would I pull that down?

**Comment by ZetaoYang** [comment]
@TragicWarrior Maybe you don't know flameshot CI building system. Travis CI using docker to build all linux distribution. So it will support ubuntu 18.04 CI build in Travis for flameshot soon.

**Comment by omkarnathsingh** [comment]
So weird that it's so hard to get a update. Development is going so good, but no attention on making release process and release on GitHub making it available with ease to all community. Not everyone is interested to build it or whatever those steps are.

Just make a release.

-------- Original Message --------

**Comment by ZetaoYang** [comment]
@omkarnathsingh @TragicWarrior NOTE: Ubuntu 17.10 and Fedora 26 will not be supported in fameshot travis ci.

**Comment by ZetaoYang** [comment]
@TragicWarrior @omkarnathsingh https://github.com/lupoDharkael/flameshot/pull/304

**Comment by omkarnathsingh** [comment]
@ZetaoYang Travis still failed :D

**Comment by ZetaoYang** [comment]
@omkarnathsingh That's travis ci timeout issue. Please see https://travis-ci.org/ZetaoYang/flameshot/builds/414384591.

**Comment by pleabargain** [comment]
confirmed flameshot NOT working in Ubuntu 18.04.1 LTS

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by Creteil** [comment]
@pleabargain 

Don't see the fact in your message...
On my side, compiling « flameshot » from github work perfect.
In case you want to try it, here is the package, just unzip it to see the .deb (see attachment).

[flameshot_0.6.0.6.g1d7186a_amd64.zip](https://github.com/lupoDharkael/flameshot/files/2313518/flameshot_0.6.0.6.g1d7186a_amd64.zip)

A++
