### ISSUE TITLE
How to capture a window just selecting the window?

### ISSUE THREAD

**Issue by ningacoding** [lupoDharkael/flameshot#225]
I dont know where to say thank you, this is the best screen shot capture tool!!
I love it.
THANK YOU ALOT!!

(just a question)
How to capture a window just selecting the window?

**Comment by lupoDharkael** [comment]
It's still in the to do list.
Duplicated issue:
https://github.com/lupoDharkael/flameshot/issues/5

**Comment by nico1988** [comment]
Still today?

**Comment by mmahmoudian** [comment]
@nico1988 read https://github.com/flameshot-org/flameshot/discussions/2060 and https://github.com/flameshot-org/flameshot/issues/5

**Comment by KES777** [comment]
@ningacoding Try `./script selectwindow`
https://github.com/flameshot-org/flameshot/issues/273#issuecomment-1165360717
