### ISSUE TITLE
IBus's lookup table were blocked when typing on text box

### ISSUE THREAD

**Issue by nicholascw** [lupoDharkael/flameshot#229]
**Describe the bug**
When typing into text box with IBus ( specifically *ibus-libpinyin* ), the look up table is hidden, while the typing is normally going on, therefore user cannot make concise decision but only by guessing, which critically affects CJK users.
**To Reproduce**
Steps to reproduce the behavior
Just type with an input method based on IBus and working with lookup table feature.
**Expected behavior**
![image](https://user-images.githubusercontent.com/7414442/40275994-7fa62b3c-5c31-11e8-9dfc-487b45607e77.png)
Normally there should be a lookup table appear below/above the input box.

![image](https://user-images.githubusercontent.com/7414442/40276199-475d20aa-5c36-11e8-8802-f8aeeeaaee71.png)
We don't have one here for flameshot on GNOME + IBus. (tried to take a picture for the inputing state.)

(KDE Plasma + fcitx works all fine, with screenshot shown below.)
![image](https://user-images.githubusercontent.com/7414442/40276176-aa9bc424-5c35-11e8-9930-775b7c46c14b.png)

**Desktop (please complete the following information):**
 - DE: [GNOME Shell 3.28.2]
 - OS: [Arch Linux]
 - Version [ AUR Package: flameshot-git r442.33377d5-1]

**Comment by lupoDharkael** [comment]
Thanks for the report, I didn't know about this.

**Comment by lupoDharkael** [comment]
I think this shouldn't be a fix inside Flameshot but of IBus itself. A fix for this would require to change how Flameshot appears on top of the desktop and it took some time to find the best way to make it work across multiple window managers.
And more important, fcitx works. So it's possible to implement the same behavior without the need of a change in the core of other programs.
Maybe this should be reported to IBus.

**Comment by nicholascw** [comment]
hmm, discussed on various communities and someone from openSUSE said openSUSE has a patched version of IBus and would handle this properly, but I haven't verified yet. This could probably an IBus's bug.
