### ISSUE TITLE
UI gets scramble when using compton

### ISSUE THREAD

**Issue by jarias** [lupoDharkael/flameshot#24]
![img_0374](https://user-images.githubusercontent.com/119519/33236249-4aab315a-d213-11e7-8be7-916689dabbd9.JPG)

Kill compton and everything is back to normal

Actual screenshot is not affected only the UI

**Comment by jarias** [comment]
Only happens when the compton backend is glx

**Comment by lupoDharkael** [comment]
I think this should be reported to Compton as every other window manager works correctly opening the capture widget.
Here are the window flags used by that widget: https://github.com/lupoDharkael/flameshot/blob/v0.4.2/src/capture/widget/capturewidget.cpp#L75

In adition the widget is shown in fullscreen mode: https://github.com/lupoDharkael/flameshot/blob/v0.4.2/src/core/controller.cpp#L67

This is the same configuration used by KDE Spectacle: https://github.com/KDE/spectacle/blob/ef85b910752f8fb160fe3378b9a82b79d1384fa6/src/QuickEditor/QuickEditor.cpp#L88

**Comment by jarias** [comment]
Will do
