### ISSUE TITLE
text tool

### ISSUE THREAD

**Issue by justislav** [lupoDharkael/flameshot#247]
Please consider adding text tool.

We use a screenshots a lot for bugreporting in our team. It is essential for us not only to make arrows or highlights but also to write a comments right on the image. So the sreenshot becomes a complete artifact for ticket rather often in our workflow.

We always use single default font size ~18..24 px just like on my screenshot )
https://i.imgur.com/M5pd2Y2.png

**Comment by justislav** [comment]
Great!

**Comment by necronoise** [comment]
Awesome, cant wait for it! Nice work :)

**Comment by mazestricks** [comment]
Great! Nice Work! Can't wait to use it with the text tool.
