### ISSUE TITLE
A way to hide sensitive info

### ISSUE THREAD

**Issue by zero-master** [lupoDharkael/flameshot#25]
Hey! I am looking for a way to hide sensitive info.

Please vote on this if you need this feature!

**Comment by lupoDharkael** [comment]
You can use the rectangle tool to hide parts of an image. I want to add a blur tool as an alternative option.

**Comment by lupoDharkael** [comment]
Solved with https://github.com/lupoDharkael/flameshot/commit/b0f385caf4c3c206eb7e509b78ac3a3617052a5f

**Comment by averissimo** [comment]
If blur is added to single words/letters then it is still readable

![image](https://user-images.githubusercontent.com/211358/34837675-76bf9a92-f6f3-11e7-982d-211d2e82ee2f.png)

**Comment by lupoDharkael** [comment]
Some users have reported it, with some combinations of colors, backgrounds and fonts it is not enough to be unreadable. It needs to be fixed.

**Comment by averissimo** [comment]
Oops seems to be reported inside #62 

Thanks
