### ISSUE TITLE
Allow notification to be dragged and dropped

### ISSUE THREAD

**Issue by magnus-gross** [lupoDharkael/flameshot#256]
Screenshot apps like spectacle allow the notification to be dragged and dropped resulting in the captured image being dropped into another app. It would be cool if flameshot would support this too. :)

If you don't know what I mean, see https://dot.kde.org/2017/01/31/plasma-59-kicks-2017-style below "Be even more productive"

**Comment by lupoDharkael** [comment]
Interesting concept, Flameshot used the general freedesktop's notification interface but I think this could be easily implemented.
