### ISSUE TITLE
How to add text

### ISSUE THREAD

**Issue by indextbag** [lupoDharkael/flameshot#258]
It's great to have this feature

**Comment by AlfredoRamos** [comment]
That feature already exist, you'll need to wait for a new release or compile from source.

See #11 ([comment](https://github.com/lupoDharkael/flameshot/issues/11#issuecomment-397700634)), #247

**Comment by moledet** [comment]
> That feature already exist, you'll need to wait for a new release or compile from source.
> 
> See #11 ([comment](https://github.com/lupoDharkael/flameshot/issues/11#issuecomment-397700634)), #247

Now 2019 and I don't see any ability to write text. The last commit was 5 months ago. The project died and no more releases?
