### ISSUE TITLE
Change of tool thickness not descriptive enough

### ISSUE THREAD

**Issue by ManuelLR** [lupoDharkael/flameshot#26]
At present, when changing the thickness of the tools there is no reference to what the new thickness is until something is drawn.

**Comment by ManuelLR** [comment]
My proposal is to show at any time the size of the tool (in the center of the pointer) knowing how thick you will draw and allowing you to quickly see the thickness you are adjusting with the mouse wheel.

**Comment by lupoDharkael** [comment]
Fixed in https://github.com/lupoDharkael/flameshot/commit/820458df89189124b5b5eb4c2c19aa6033857c14
