### ISSUE TITLE
Multiple markers color 

### ISSUE THREAD

**Issue by shaygover** [lupoDharkael/flameshot#271]
Is it possible to use more that one marker color. For example:
Marker one side of the screenshot yellow and the other blue?

**Comment by AlfredoRamos** [comment]
After choosing Marker, right clicking the screen selection allows you to choose a different color.

I'm not sure about the latest released version, but if you compile Flameshot from source you can also use the <kbd>Space</kbd> bar to show a panel where you can choose a color too.

**Comment by noraj** [comment]
@AlfredoRamos Can you talk about that (making color picker + History appearing by pressing `Space`) on the README, that is very precious.
