### ISSUE TITLE
Add a "counter" feature like greenshot

### ISSUE THREAD

**Issue by bbigras** [lupoDharkael/flameshot#275]
I use Greenshot on Windows and it's pretty nice to be able to add "counters" to show people the order of the steps, like this:

![image](https://user-images.githubusercontent.com/24027/43006773-94676916-8c04-11e8-9d15-f47c13a9c62b.png)

**Comment by Rmano** [comment]
This is a duplicate of https://github.com/lupoDharkael/flameshot/issues/187
