### ISSUE TITLE
GTK warning Theme parsing error

### ISSUE THREAD

**Issue by Philippe-M** [lupoDharkael/flameshot#280]
**Describe the bug**
Flameshot does not launch and in my terminal I have the error: 

`(flameshot:613): Gtk-WARNING **: 09:31:32.950: Theme parsing error: gtk.css:3841:23: Junk at end of value for outline-offset`

**To Reproduce**
Start flameshot

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Fedora 
 - Version 28 (last update)

**Comment by AlfredoRamos** [comment]
The issue is not related to Flameshot, is a GTK theme issue.

Update your GTK theme, you can ignore the warning or report to its creator.

Related issues #193

**Comment by vinceliuice** [comment]
Now fIxed!

**Comment by chiddekel** [comment]
Level higher - how resolve parsing error <data>...
Gtk-WARNING **: 15:21:41.659: Theme parsing error: <data>:1:34: Expected ')' in color definition

**Comment by AlfredoRamos** [comment]
@chiddekel You should seek for support with the author of the theme you're using, it's not an issue of Flameshot.
