### ISSUE TITLE
Files created by Flameshot can not be accessed via windows.

### ISSUE THREAD

**Issue by zaferakalin** [lupoDharkael/flameshot#295]
**Describe the bug**

The file created with Flameshoot on Fedora 28 x64 is not accessible via windows.
I tried to saving to the ntfs partition that was mounted directly. Saving takes place. Access is provided via Fedora. Access through the Windows operating system is not allowed.

**To Reproduce**

Each successful screen image file has this problem.

**Expected behavior**

The screen image is recorded. The file is saved directly the ntfs partition or home directory and copied or moved to ntfs partition. The file is accessed via both Fedora and Windows.

**Desktop (please complete the following information):**

 - OS: Fedora 28
 - Flameshot Compiled with QT 5.10.1

**Comment by zaferakalin** [comment]
There is no problem when I copy or move any file that exists in Fedora. Interestingly, only the files created by Flameshot cause problems.

**Comment by Rmano** [comment]
Check if the file has a colon `:` in its name. That makes the file name invalid in Windows...

**Comment by zaferakalin** [comment]
Yeah, I guess I did not pay attention. This is great news, I've updated the file name appropriately and there is no problem.
