### ISSUE TITLE
Please allow free naming of the screenshots

### ISSUE THREAD

**Issue by Raitsa** [lupoDharkael/flameshot#298]
As title: please allow free naming of the screenshots, useful for us who are not native english speakers etc.

Personally I would usually name it like this:

kuvakaappaus-1

kuvakaappaus-2

kuvakaappaus-3

etc.

**Comment by lupoDharkael** [comment]
You can do it, check in the second tab of the configuration window (open the window with right click in the tray icon, and selecting the "configuration" menu item).
