### ISSUE TITLE
Please enable Travis CI

### ISSUE THREAD

**Issue by probonopd** [lupoDharkael/flameshot#30]
Looks like Travis CI is not enabled on your project:
https://travis-ci.org/lupoDharkael/flameshot

Please enable it.
https://docs.travis-ci.com/user/getting-started/

**Comment by lupoDharkael** [comment]
done, and thanks!

**Comment by probonopd** [comment]
Thank you. Have you considered to provide an AppImage?

**Comment by lupoDharkael** [comment]
Sure! I've been busy with other stuff but I want to release a new version soon with a .deb and an AppImage package as it would be very handy for the users.
