### ISSUE TITLE
High DPI and Blur Tool

### ISSUE THREAD

**Issue by ryanerwin** [lupoDharkael/flameshot#300]
**Describe the bug**
When using a High DPI display (I have scaling set at `2.0`) blur filter use and undo is still based on an underlying Non-High DPI display buffer

**To Reproduce**
Steps to reproduce the behavior
1) Launch flameshot
2) Select an area to capture
3) Activate the `Blur` tool
4) Begin to Blur a portion of the image - **PROBLEM: the blurred area doesn't represent the HiDPI display**

![image](https://user-images.githubusercontent.com/2156415/43761986-4bb5bd04-9a59-11e8-81aa-fc1b8730829d.png)

5) Undo the action - **PROBLEM: undo the blur a low DPI artifact is shown in place of the blur...**

![image](https://user-images.githubusercontent.com/2156415/43762285-181b962a-9a5a-11e8-8434-f7042f6b1fe2.png)

**Expected behavior**
Expected the blur tool to work

**Desktop (please complete the following information):**
 - OS: Arch Linux, LSB v1.4, linux 4.17.12.arch1-1
 - Flameshot-Git from AUR: flameshot-git-r471.046170d-1-x86_64.pkg.tar.xz

**Comment by PeterCxy** [comment]
Confirmed on my HiDPI setup. I'll try to look into this issue.
