### ISSUE TITLE
Flameshot stopped working

### ISSUE THREAD

**Issue by michaldybczak** [lupoDharkael/flameshot#307]
**Describe the bug**
This isn't a bug per se since probably it only affects me. Not sure what happened (maybe an update) but when I try to use flameshot it doesn't starts. I then checked it in terminal and there is no output, no even a single word.
I tested both flameshot-git from AUR and from Manjaro repo. Both are not working.
If that's not the place to ask such questions, just let me know and I close this topic.

Does someone knows how to approach such issue when there is no info to debug?

Thanks.

**To Reproduce**
Open flameshot from start or with command: flameshot. Nothing happens

**Expected behavior**
Flameshot starts

**Desktop (please complete the following information):**
 - OS: Manjaro KDE

**Comment by AlfredoRamos** [comment]
Try to run the following and post its output:

```shell
pkill flameshot
flameshot --version
```

Or better yet, run the following (you might need to install `gdb` first):

```shell
gdb -ex run flameshot
```

And when it prompts for a command `(gdb) `, just type `bt` and post the output.

**Comment by michaldybczak** [comment]
pkill flameshot - no output, terminal jumps to another line ready for next command

```

```
$ flameshot --version
Flameshot v0.5.1-107-gb0000f8
Compiled with Qt 5.11.1

```
$ gdb -ex run flameshot
GNU gdb (GDB) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from flameshot...(no debugging symbols found)...done.
Starting program: /usr/bin/flameshot 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffed86b700 (LWP 4499)]
[New Thread 0x7fffdb844700 (LWP 4501)
```

The last one hangs as if I run a program, meaning I have to quit it to return to normal command.
It never prompted me for anything.

**Comment by farseerfc** [comment]
Have you try `flameshot gui` command to take a screenshot?

**Comment by michaldybczak** [comment]
Wow, that did work:

![screenshot-2018-08-12-09-06-10](https://user-images.githubusercontent.com/10132958/43999563-118b332a-9e0f-11e8-82e9-d977ef3527a6.png)

So flameshot is working but the flameshot command and the launch icons stopped working then. Also, before when I was typing flameshot in start menu, I had two results, flameshot itself and its configuration utility. Now it just finds flamshot only.

**Comment by hosiet** [comment]
Look, I've got a suggestion:

1. Restart your computer
2. Invoke flameshot via start menu (and yes, it seems that nothing happens, right?)
3. Click the little triangle at your KDE tray area: is the flamrshot icon hidden inside?

If yes, it's that you misused the KDE Desktop Environment, not the bug from flameshot side. If no, please describe what did you see then.

**Comment by farseerfc** [comment]
The plain `flameshot` command and icon should start in background. There should be an icon for flameshot in the KDE system tray area, but it might be hidden in the notification dropdown by default.
You can config KDE systray to always show flameshow icon like this:
![image](https://user-images.githubusercontent.com/861563/43999595-a060165c-9e4a-11e8-8dab-00ec6e9aabf2.png)

**Comment by linuxkathirvel** [comment]
> Look, I've got a suggestion:
> 
> 1. Restart your computer
> 2. Invoke flameshot via start menu (and yes, it seems that nothing happens, right?)
> 3. Click the little triangle at your KDE tray area: is the flamrshot icon hidden inside?
> 
> If yes, it's that you misused the KDE Desktop Environment, not the bug from flameshot side. If no, please describe what did you see then.

Thanks. It is working in Arch KDE after set it as 'Always shown' in System Tray.
