### ISSUE TITLE
Add text to screenshot?

### ISSUE THREAD

**Issue by DomingoMontoya** [lupoDharkael/flameshot#315]
Love this app. The only feature I'm missing personally, that I like in shutter and greenshot, is ability to add text to an image.

Thanks.

**Comment by DomingoMontoya** [comment]
Nope. Repos have same version as github, but fetched that one anyway. Still no text option.

**Comment by sterndata** [comment]
My version is built from Github. I did a fresh pull and recompile this morning.  (Aside: I see it's now in the Fedora repos, so maybe i'll switch over to that soon.)

**Comment by DomingoMontoya** [comment]
Maybe there's some optional package I'm missing. I'll have to try to build.

**Comment by AlfredoRamos** [comment]
It hasn't been released yet, but you can use a deb from Travis builds:

https://travis-ci.org/lupoDharkael/flameshot

The link is at the bottom of the build log.

- https://transfer.sh/kW1hE/flameshot_0.5.1-xenial-x86_64_x86_64.deb
- https://transfer.sh/hMia1/flameshot_0.5.1-bionic-x86_64_x86_64.deb

Build the application yourself, or wait until a new version is released.

**Comment by DomingoMontoya** [comment]
Thanks. The bionic deb worked. Building it myself did not. No idea why.

**Comment by changchichung** [comment]
@AlfredoRamos  
those two links are both dead. Can you upload again or is there any documents teach how to build in ubuntu 18.04 ?

**Comment by AlfredoRamos** [comment]
@changchichung Files from transfer.sh are only stored for 14 days.

As previously said, you can get links from [Travis build logs](https://travis-ci.org/lupoDharkael/flameshot), choose your distro (`DIST` variable) and at the bottom of the log it's the link.

You can see the [README.md](https://github.com/lupoDharkael/flameshot) file for compilation instructions.

I don't use Ubuntu, but the compilation process is the same for any distro.
