### ISSUE TITLE
Add ability to add text onto screenshot

### ISSUE THREAD

**Issue by DanitiKain** [lupoDharkael/flameshot#316]
I just would love to have the option to put text on the screen next to what I am pointing out with say an arrow. 

https://i.imgur.com/cYbiwlC

**Comment by TragicWarrior** [comment]
@DanitiKain , it does.  It's included in build 0.60.

**Comment by hosiet** [comment]
If you are indeed using flameshot 0.6.0, you will have to enable the text function in the config first. Please open the config window and examine the tool list again to ensure that the text tool is selected.

**Comment by DanitiKain** [comment]
Ok that works thanks for follow-up
