### ISSUE TITLE
no tool icons

### ISSUE THREAD

**Issue by uuencode** [lupoDharkael/flameshot#335]
I searched the issues and couldn't find anything similar.

**Flameshot version**
0.6.0 installed from Solus Software Center

**Describe the bug**
No icon visible on tool buttons.
![screenshot from 2018-09-04 13-12-14](https://user-images.githubusercontent.com/19911332/45025651-b8d48400-b044-11e8-8f87-57ae72f053b1.png)

**System Information**
Solus Gnome

**Comment by AlfredoRamos** [comment]
Is the [Qt SVG](https://doc.qt.io/qt-5/qtsvg-index.html) module installed? What's the output of the following command?

```shell
sudo updatedb
locate -e libqsvg
```

Note: You might need to install `mlocate` to use the `updatedb` and `locate`.

Does running the application from your terminal throw any error?

**Comment by uuencode** [comment]
Thank you AlfredoRamos. Installing QT SVG fixed the issue. I wonder why it was not a dependency.

**Comment by hosiet** [comment]
@uuencode Please contact with flameshot's packager of Solus and report the bug.

**Comment by mbrodala** [comment]
Thanks for the hint, the Debian package suffers from the same issue.

**Comment by hosiet** [comment]
I just made an upload in Debian (0.6.0-11) which adds the missing dependency (libqt5svg5). A Pull Request was proposed (#481) to fix this issue in the upstream `debian` directory.

**Comment by mbrodala** [comment]
@hosiet Thanks a lot!

**Comment by Miaourt** [comment]
mmmh, I get the same issue on Fedora 30

Yet, can't find any qtsvg lib on the repo @.@

**Comment by aemyers** [comment]
The AppImage package is doing this on RHEL7. I tried installing qt5-qtsvg but still no luck. Any other hints?

**Comment by justanh** [comment]
Installing qt5svg did not solve it for me, what do I do?

**Comment by Miaourt** [comment]
@justanh did you restarted Flameshot ? (Or in the doubt, the whole system, because Flameshot launch some background process)

**Comment by justanh** [comment]
Oh yes restarting the whole system solved the issue, thanks
