### ISSUE TITLE
Compilation error on 18.04 

### ISSUE THREAD

**Issue by Rmano** [lupoDharkael/flameshot#338]
**Flameshot version**
1d7186a2f08284e8182ee14d54f5803cb6aa0ca8

**Describe the bug**
Do not compile anymore on Ubuntu 18.04

**To Reproduce**
qmake && make

**Expected behavior**
compilation of flameshot

**System Information**
Ubuntu 18.04 w/x11

```
[...]
Updating '/home/romano/software/flameshot/translations/Internationalization_pl.qm'...
Removing translations equal to source text in '/home/romano/software/flameshot/translations/Internationalization_pl.qm'...
    Generated 146 translation(s) (146 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
Project ERROR: Unknown module(s) in QT: svg
```

**Comment by hosiet** [comment]
According to README.md, similar to Debian, you must install a series of build dependencies on Ubuntu prior to building. Please refer to [https://github.com/lupoDharkael/flameshot#debian](https://github.com/lupoDharkael/flameshot#debian), install required packages and try again.

**Comment by Rmano** [comment]
Ok --- I supposed that the fact that it compiled on 16.04 meant that it would on 18.04. I missed the qt-svg  bit. My apologies.
