### ISSUE TITLE
Release 0.6.0 is missing in Ubuntu 18.04 Bionic archives

### ISSUE THREAD

**Issue by the-spyke** [lupoDharkael/flameshot#341]
**Flameshot version**

Flameshot 0.5.1-1(Debian)

**Describe the bug**

The v0.6.0 release is available only for yet not released Ubuntu 18.10 Cosmic.

**To Reproduce**

```shell
$ sudo apt install flameshot
$ flameshot --version
Flameshot 0.5.1-1(Debian)
Compiled with QT 5.9.4
```

**Expected behavior**

Should be 0.6.0

**System Information**

Ubuntu 18.04

**Comment by hosiet** [comment]
Ubuntu 18.04 is already released thus there will only be security updates or updates to important fixes, no new version for random softwares in the main software repository. 

Pushing new version into -backports repository might be possible but we need a Ubuntu Developer to achieve that. I am only a Debian Developer, not a Ubuntu Developer so I can do little for that, sorry.

  * recall that Ubuntu will automatically drag packages from Debian periodically for Ubuntu's new release but that does not apply to already-released Ubuntu versions (say 18.04).

**Comment by hosiet** [comment]
Oh btw, the flameshot upstream has already provided deb packages specific to Ubuntu 18.04 on the GitHub release page so you may download and use that one. That package is not from Linux distribution but still may satisfy your needs.

**Comment by the-spyke** [comment]
@hosiet Thanks for such a detailed answer. I've just realized that I had no idea how Ubuntu packaging works. Having the `flameshot` updated only once in 2 years (if I stick to LTS releases) sounds terrible. Alternatives are backports or PPAs. Both are missing, but I've already downloaded and installed the `deb`, which is nice.
