### ISSUE TITLE
Created 2 files in tmp when I do a section screenshot

### ISSUE THREAD

**Issue by simonbcn** [lupoDharkael/flameshot#349]
**Flameshot version**
Flameshot v0.6.0-10-g415b059
Compiled with Qt 5.11.1

**Describe the bug**
I have defined as destination of my screenshots the `/tmp` folder (_so that they are erased as soon as I restart or turn off the computer_).
The "problem" is that when I make a screenshot of a section, `flameshot` generates 2 screenshots in `tmp`: one with the full screen and another with the section I have selected, both with similar names.
![captura_20180919_143758](https://user-images.githubusercontent.com/428231/45753608-a7c96c80-bc19-11e8-905e-651b08b0d0a1.png)

**To Reproduce**
Make a section screenshot 

**Expected behavior**
The full screenshot should be deleted once the section screenshot has been saved, or give a different name from the flameshot schemes (_something like a random number + a date, without extension_) or create them in a temporary folder within tmp.

**System Information**
Arch Linux
GNOME Shell 3.30.0 on Wayland

**Comment by AlfredoRamos** [comment]
I can't reproduce (Arch Linux, LXQt 0.13.0), the temporary one is deleted.

It would be good that it is tested on other distros.

**Comment by simonbcn** [comment]
I think the problem is how `flameshot` make the screenshots on Wayland. In Gnome on X there is not this problem.

**Comment by lupoDharkael** [comment]
yes, flameshot tells the shell to save the screenshot in /tmp because in wayland you have to use the dbus API of Gnome shell to take screenshots.
Maybe flameshot should delete the original created by the shell after it is loaded.

**Comment by simonbcn** [comment]
Yes, I agree that flameshot should delete the capture created by DBus once it is no longer needed.

**Comment by lupoDharkael** [comment]
Fixed here: https://github.com/lupoDharkael/flameshot/commit/affba85666b78d62da7e9ec0858fd4f0ddda0752
