### ISSUE TITLE
Pin tool not pinning to original position on Ubuntu 16.04

### ISSUE THREAD

**Issue by elonliu** [lupoDharkael/flameshot#350]
**Flameshot version**

v0.6.0

**Describe the bug**

Copy an area of the screen and pin it using the pin tool. The pinned picture doesn't appear at the same position as it was, but moved a little.

Not sure this is a bug, but if it stays exactly where it was, it could be more helpful in some cases.

![image](https://user-images.githubusercontent.com/5549178/45808233-e9c8e000-bcf7-11e8-8eef-961ccc11df9d.png)

**To Reproduce**

On Ubuntu 16.04 screen, begin screenshot to copy a region and click the pin tool button.

**Expected behavior**

The pinned picture stays exactly where it was copied

**System Information**

Ubuntu 16.04 LTS

**Comment by ZetaoYang** [comment]
@elonliu Yes, I know this situation, it's  not a bug.

**Comment by ZetaoYang** [comment]
@elonliu Please see #352.

**Comment by elonliu** [comment]
Cool!
