### ISSUE TITLE
Flameshot slow on copying to clipboard

### ISSUE THREAD

**Issue by wdtbd** [lupoDharkael/flameshot#353]
Version:
Flameshot v0.6.0
Compiled with Qt 5.11.1
Arch with i3wm

After last update, flameshot takes forever to copy image to clipboard.
Saving image works, but then when starting flameshot gui again it takes forever(~20s).
no errors when running from console or from gdb.

**Comment by antoniotorresm** [comment]
Are you using any notification daemon? I had this same problem and it was fixed when running one. (`dunst`, for example). Alternatively, you can deactivate Flameshot's desktop notifications.

**Comment by wdtbd** [comment]
Installing dunst solved it, thanks @antoniotorresm, closing issue.

**Comment by emielvanberlo** [comment]
I use XFCE but had some KDE traces left.
my notifications didn't work.
remove plasma-workspace fixed my notifications and flameshot.

**Comment by prateekamana** [comment]
Thanks for that [emielvanberlo](https://github.com/emielvanberlo), that solved the issue on my QTile as well, the problem started after I installed Plasma.

**Comment by officialbishowb** [comment]
Hey, I'm having the problem that when I select an area and try to copy it (CTRL + C), it takes about 1 minute (until the flame icon reappears) before I can paste the image anywhere, and when I paste it before that, the application I want to paste to crashes. What could be the problem?
