### ISSUE TITLE
Icons with numbers

### ISSUE THREAD

**Issue by KOT040188** [lupoDharkael/flameshot#359]
The shutter app has a tool that adds icons with numbers https://cloud.mail.ru/public/A7bk/QzFvUBaS8 I often use this. It is faster and more convenient than typing numbers on the keyboard. Is it possible to add such a tool?

**Comment by KOT040188** [comment]
https://yadi.sk/i/anVyesmsT3bDaA  Tell me in which service to post a picture?

**Comment by AlfredoRamos** [comment]
Yes, this is indeed a duplicate issue of the one I linked.

**Comment by KOT040188** [comment]
Can I wait for this tool to be added?

**Comment by lupoDharkael** [comment]
I'm closing this as it's a duplicate. I've started university classes so I don't have much time, but I'll try to work on a few features/fixes soon.
This one is a not that hard to implement feature.
