### ISSUE TITLE
Enter key doesn't copy content to clipboard

### ISSUE THREAD

**Issue by Streppel** [lupoDharkael/flameshot#362]
**Flameshot version**
0.6.0

**Describe the bug**
The return key is commonly called as _enter key_ in many times during our day to day usage, as opposed to _return key_, at least from my experience. So, when we use a big keyboard with a dedicated numeric keyboard on the side, we usually expect the _return key_ to have the same behavior as the _enter key_.

On flameshot, _return key_ saves the selection on GUI mode to the clipboard, but the _enter key_ does not replicate this behavior. I stumbled upon this a couple of times when I reached the numeric enter key, as it is closer to the mouse.

**To Reproduce**

- Start GUI mode
- Make a selection
- Press "Enter" on  numeric keyboard
- Nothing Happens 

**Expected behavior**
- Start GUI mode
- Make a selection
- Press "Enter" on  numeric keyboard
- Content should be copied to clipboard 

**System Information**
Ubuntu 16.04

This is nothing critical, so please feel free to reply in case you don't agree

btw much love from brazil <3 flameshot is great

**Comment by alexamy** [comment]
Hi! I encounter similar misleading behaviour too. I'm using Ubuntu 18.04.2 and just install flameshot.

I type `flameshot gui -p ~/Pictures` in terminal, select some region on the screen, and I expect that if I press 'enter' (or 'return') key on my keyboard, the region will be saved in `~/Pictures`. But I have to manually click the save button to do so. It's very inconvenient.

**Comment by alexamy** [comment]
UPD: I've updated flameshot version to 0.6.0. Now 'enter' key copies selection to clipboard. I think it is convinient when I'm using `flameshot -c`, but why do I need that when I'm using just `flameshot -p`?

**Comment by Streppel** [comment]
@alexamy both enter and return keys behave alike in this situation? This PR was intended to make the enter key behave exactly as the return key does

**Comment by alexamy** [comment]
@Streppel Both keys are copying selection to clipboard. But I dont fully understand your intention here. If I'm using `flameshot gui -p ~/Pictures` command, first of all I expect flameshot to save screenshot to `~/Pictures`. I can achieve this by clicking 'Save' button in gui selection mode. 
But I also expect a shorter way to do this by just pressing 'Enter' (or 'Return') key. At this moment If I press one of these keys, selection is just copied to clipboard, but isn't saved at `~/Pictures`. I find this as a misleading behavior.

**Comment by Streppel** [comment]
@alexamy I agree with you, this is misleading behavior. However, it's not related to this issue (362), so I believe the best thing to move on with this is to open a different issue and keep track on it.
