### ISSUE TITLE
Shell scripts - Port to POSIX sh + Prevent globbing and word splitting

### ISSUE THREAD

**Issue by burianvlastimil** [lupoDharkael/flameshot#368]
I am not familiar with Pull requests, so excuse me for posting it here:
I suggest for all of the shell scripts to be modified into POSIX sh.
While fixing potential bugs as I saw in the below example.
For example one file: ```linux_after_success.sh``` does work with strings
in a way not preventing globbing and word splitting; I fixed that.

For more info on this topic visit:
https://github.com/koalaman/shellcheck/wiki/SC2086

In addition, I would like to review all your shell scripts in more detail than this.

How shall I proceed?

```
#!/bin/sh

set -e

DIST_PATH=dist

if [ "${DIST}" = "trusty" ]
then
	travis_retry curl \
		--upload-file \
		"${DIST_PATH}/flameshot_${VERSION}_${ARCH}.${EXTEN}" \
		"https://transfer.sh/flameshot_${VERSION}_${ARCH}.${EXTEN}"
else
	case "${OS}" in
		"ubuntu"|"debian")
			travis_retry curl \
				--upload-file \
				"${DIST_PATH}/flameshot_${VERSION}_${DIST}_${ARCH}.${EXTEN}" \
				"https://transfer.sh/flameshot_${VERSION}_${DIST}_${ARCH}.${EXTEN}"
			;;
		"fedora")
			travis_retry curl \
				--upload-file \
				"${DIST_PATH}/flameshot_${VERSION}_fedora${DIST}_${ARCH}.${EXTEN}" \
				"https://transfer.sh/flameshot_${VERSION}_fedora${DIST}_${ARCH}.${EXTEN}"
			;;
	esac
fi
```

**Comment by AlfredoRamos** [comment]
Is there any benefit to change it to POSIX? because they're only used on tests and in those system Bash is available, or is it for testing on BSD systems?

Other changes are indeed good.

**Comment by burianvlastimil** [comment]
I thought it would just be a good idea, no matter, as you pointed out, on those systems where it is being installed, there actually always is Bash, so I no longer see reason for this. You may close the issue.

**Comment by AlfredoRamos** [comment]
@burianvlastimil It was genuine question, it was not a criticism to prevent you from making changes.

I use bash in all my scripts, so I just wanted to know if I should change them too, nothing else.

**Comment by burianvlastimil** [comment]
Ok, then. I, on the other hand, write pure POSIX shell scripts.

Reason: Bash is not portable. And as such is unusable for creating scripts that should run on all kinds of Linux systems.

**Comment by Lin-Buo-Ren** [comment]
I fail to see how much more systems will benefit if all the systems intended to expect it run on has a relatively recent Bash.

On the other hand, we probably should rather improve the current Bash scripts to be more tolerant of some [classic pitfalls](https://github.com/koalaman/shellcheck#gallery-of-bad-code) by the help of ShellCheck

**Comment by burianvlastimil** [comment]
It really seems that it would not bring anything to your project. I leave it to you. Closing this issue.
