### ISSUE TITLE
Open existing image file to annotate

### ISSUE THREAD

**Issue by kramer65** [lupoDharkael/flameshot#369]
I sometimes have an existing image to which I want to add some annotations (text/arrows/etc). I would like to be able to open an existing image file to edit it using Flameshot. I tried dropping a file on the icon in the top bar in Gnome, but that didn't work. 

Anyway, keep up the good work!

**Comment by AlfredoRamos** [comment]
Duplicate issue, see #240

**Comment by jpaine619** [comment]
It's been 6 years.... They aren't gonna bother.. That's why this project is crap.  Pure garbage that doesn't have the concept of "I don't want to annotate the whole damn thing at this exact moment"
