### ISSUE TITLE
Cannot locate package flameshot

### ISSUE THREAD

**Issue by metalcamp** [lupoDharkael/flameshot#370]
**Flameshot version**

**Describe the bug**
Debian package cannot be found.

**To Reproduce**
`
sudo apt install flameshot
`

**Expected behavior**
Well, I expected to install package.

**System Information**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by metalcamp** [comment]
Sure, I was surprised I haven't found it with apt. OTOH command works on Ubuntu 18.04.

**Comment by hosiet** [comment]
@metalcamp flameshot did not exist yet when Ubuntu 16.04 released. That's the root reason...
