### ISSUE TITLE
Need "Write Text" option

### ISSUE THREAD

**Issue by avndp** [lupoDharkael/flameshot#385]
First of all, I thank infinite times to the people who made this lovely software. I've migrated from Windows to Ubuntu few months back and missing "Lightshot" of the windows application a lot. As of now for taking snaps, I have to use GIMP to crop or add remarks. Now it's easy with Flameshot.

If one more feature is added, flameshot would be perfect.. That is "Write Text" option as in Lightshot. It helps to add text over screenshot directly before saving.

**Comment by Rmano** [comment]
It's already implemented.  Please look at https://github.com/lupoDharkael/flameshot/issues/11

**Comment by AlfredoRamos** [comment]
It was added in the version 0.6.0, if your distro doesn't have that version in its repositories, you can download the `*.deb` package listed in the release page:

https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0
