### ISSUE TITLE
Cannot mix incompatible Qt library

### ISSUE THREAD

**Issue by doofy** [lupoDharkael/flameshot#402]
**Flameshot version**
```
Flameshot v0.6.0-23-g35459e1
Compiled with Qt 5.11.2
```

**Describe the bug**
Flameshot starts but as soons as you click the systray icon you get this:
```
Cannot mix incompatible Qt library (version 0x50b01) with this library (version 0x50b02)
```
**To Reproduce**
start flameshot (from a console) and click systray icon

**Expected behavior**
normally the flameshot screenshot function would start and display flameshot UI

**System Information**
gentoo

**Comment by AlfredoRamos** [comment]
How did you install the application?

Check the output of the following commands, maybe they provide more information:

```shell
QT_DEBUG_PLUGINS=1 flameshot
gdb -ex run flameshot
```

**Comment by jgedri** [comment]
I'm having the same problem on Solus. Anything based on qt throws this error.

**Comment by doofy** [comment]
I think this was a packaging mistake. (See https://github.com/jorgicio/jorgicio-gentoo/pull/159#event-2160137472)

Sorry for the unnecessary noise generated by me.
