### ISSUE TITLE
Color picking is unusable on touchpad

### ISSUE THREAD

**Issue by Gotterbild** [lupoDharkael/flameshot#406]
Despite the fact that it is a feature request, for me it is more like a bug that is blocking me from using the app.

I'm using a notebook and do not use mouse at all. I can understand that it is quite useful to pick a color with clicking and holding right mouse button. But it makes it impossible to pick a color with touchpad that features only left click (like mine on Xiaomi Notebook Air). On touchpad it is easy to perform double click (two fingers touch), but it is very hard to perform right-click-and-hold.

I can imagine two ways to fix a problem:
1. Add an option to config to change behavior from right-click-and-hold to right-click to open colors and left click to pick a color.
2. Add a color picker to instruments.

I think that second option covers more use cases. 

Thanks for a good app.

**Comment by AlfredoRamos** [comment]
Which version are you using?

Since version 0.6.0 there's a side-panel (<kbd>Spacebar</kbd>) where you can pick a color, and if you compile the application from the master branch, you can also change the thickness.

See [Keyboard shortcuts](https://github.com/lupoDharkael/flameshot#keyboard-shortcuts) in the README for more info.

**Comment by Gotterbild** [comment]
I'm using linux version of app on Ubuntu, which I didn't compile - just installed it via `sudo apt install flameshot`.

Version is `flameshot/bionic,now 0.5.1-2 amd64` (got from `apt search flameshot`).

> Since version 0.6.0 there's a side-panel (<kbd>Spacebar</kbd>) where you can pick a color.

Nothing happens when I hit spacebar when area for capture is selected and Flameshot instruments are shown.

Also, I have no <kbd>Spacebar</kbd> mentioned in keyboard shortcuts inside app (it's localized in Russian):
![image](https://user-images.githubusercontent.com/23502743/49033349-008c2700-f1c0-11e8-85de-63fbd7afb6b2.png)

**Comment by AlfredoRamos** [comment]
As I said in my previous comment, that feature was added in version 0.6.0, you're using 0.5.x so you can't use that feature.

You can ether compile the application yourself or install a `*.deb` package for your Ubuntu version in the release page:

https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0

**Comment by Gotterbild** [comment]
I've installed a deb package and have no issues now. Thanks, @AlfredoRamos
