### ISSUE TITLE
Make transparency configurable

### ISSUE THREAD

**Issue by louwers** [lupoDharkael/flameshot#41]
I'd like to be able to choose how dark the non-screenshotted part of the screen is prior to taking a screenshot. On my screen it happens to be barely visible, making it hard to take a screenshot.

A slider from 0% to 80% on the configuration editor would be ideal for this.

**Comment by lupoDharkael** [comment]
I like the idea. For Plasma users the cross mouse pointer is hard to see in a light background, but a very dark background makes hard to see what's behind, the users should be able to adjust de level of transparency.

**Comment by lupoDharkael** [comment]
https://github.com/lupoDharkael/flameshot/commit/2932e5930d852eba5f8654eb8d8ff9e5febbe1a8

**Comment by ZetaoYang** [comment]
@lupoDharkael I think it should also show the current percentage.

![image](https://user-images.githubusercontent.com/10769951/34472812-056e21ce-efa5-11e7-83e5-0e2c721ff588.png)
