### ISSUE TITLE
Provide Snap package for Flameshot

### ISSUE THREAD

**Issue by Lonniebiz** [lupoDharkael/flameshot#411]
I'd like to install Flamshot via snap, but I couldn't find it here:
https://snapcraft.io/store

**Comment by julian-alarcon** [comment]
This is a duplicated request from https://github.com/lupoDharkael/flameshot/issues/342

Can you close it please?

Thank you!

**Comment by hurricanehrndz** [comment]
@Lonniebiz 

If you wish to build the snap yourself without any footprint follow the following directions:
```
sudo snap install lxd
sudo snap install snapcraft
sudo usermod -aG lxd  $USER
sudo lxd init
git clone https://github.com/lupoDharkael/flameshot
cd flameshot
snapcraft cleanbuild
sudo snap install --dangerous flameshot_git_amd64.snap
```

If you weren't already part of the lxd group you might need to log in and out. Additionally, 342 can be closed within 15 minutes if someone would enable the snapbuilds on travis.

**Comment by hurricanehrndz** [comment]
![flameshot](https://user-images.githubusercontent.com/5804237/49174679-1c98e100-f304-11e8-9a20-436ad7c83d04.png)
![flameshot-config](https://user-images.githubusercontent.com/5804237/49174685-1f93d180-f304-11e8-85b8-404c08678578.png)

Here are some images of the app running as a snap on KDE.

**Comment by ZetaoYang** [comment]
@hurricanehrndz That UI effect is not normal!

**Comment by hurricanehrndz** [comment]
@ZetaoYang can you please expand? Is it the fact that it is not in dark mode?

**Comment by ZetaoYang** [comment]
@hurricanehrndz The UI components of flameshot should be gtk+ UI style.

**Comment by Lonniebiz** [comment]
This is still an open issue, but I'm closing #411, because it is a duplicated of #342.

**Comment by hurricanehrndz** [comment]
By UI style I'm guessing you are referring to the host desktop environment
theme. Is that correct? If so that is a drawback for snap and QT.
https://bugs.launchpad.net/bugs/1585332

**Comment by ZetaoYang** [comment]
@hurricanehrndz Yes, you're right.

**Comment by hurricanehrndz** [comment]
There may be hope, but the last time I tried this didn't work:
https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
I should probably also reference the kde framework snap to make this snap
smaller.

**Comment by ZetaoYang** [comment]
@hurricanehrndz Thanks, I'm doing snap building on circleci. I plan move snap, flatpak, appimage to [circleci](https://circleci.com).

**Comment by hurricanehrndz** [comment]
@ZetaoYang,

Are you a repo owner for this project?

**Comment by ZetaoYang** [comment]
@ZetaoYang No, I'm not.

**Comment by hurricanehrndz** [comment]
Well that's unfortunate, because it will be really tough to get auto
builds, which is why I have the opened issue.
On Thu, Nov 29, 2018 at 9:13 AM Ahmed Zetao Yang
<notifications@github.com> wrote:
>
> @ZetaoYang No, I'm not.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Regards,

Carlos Hernandez
