### ISSUE TITLE
Installation failed under ubuntu17.04

### ISSUE THREAD

**Issue by hnyer** [lupoDharkael/flameshot#413]
![qq 20181204173208](https://user-images.githubusercontent.com/5989755/49440787-90a12080-f7ff-11e8-873e-ea7fcb79e38b.png)
![qq 20181204173256](https://user-images.githubusercontent.com/5989755/49440791-93037a80-f7ff-11e8-99d4-401ff9e34f88.png)

**Comment by hosiet** [comment]
Ubuntu 17.04 is not a long-term support (LTS) release and it's support has already ended. Please upgrade your Ubuntu version to 18.04 LTS or higher.

**Comment by hnyer** [comment]
thanks a lot
