### ISSUE TITLE
Wayland and Fedora29

### ISSUE THREAD

**Issue by porjo** [lupoDharkael/flameshot#421]
**Flameshot version**
0.6.0

**Describe the bug**
Attempting to use Wayland results in core dump.

```
$  QT_QPA_PLATFORM=wayland flameshot
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

**To Reproduce**
Run with `QT_QPA_PLATFORM=wayland flameshot`

**Expected behavior**
Should run or error and exit gracefully.

**System Information**
Fedora 29 using Wayland

**Comment by ZetaoYang** [comment]
@porjo Exactly, fedora 29 uses XWayland.

**Comment by thebitstick** [comment]
If you don't have qt wayland support installed, running qt with wayland won't work, it's simple.

**Comment by ZetaoYang** [comment]
@porjo `sudo dnf install qt5-qtwayland`

**Comment by thebitstick** [comment]
Do you have a Tray icons extension installed on gnome?

**Comment by porjo** [comment]
> Do you have a Tray icons extension installed on gnome?

Yes

**Comment by ZetaoYang** [comment]
@porjo Please try https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by porjo** [comment]
> @porjo Please try https://extensions.gnome.org/extension/615/appindicator-support/

I uninstalled Topicons and installed Appindicator, and now flameshot trayicon appears using wayland. Thanks!
