### ISSUE TITLE
Separate icon for tray/panel

### ISSUE THREAD

**Issue by erikdubois** [lupoDharkael/flameshot#445]
can you add an tray-icon to your application so we can theme our icons so that they look the same.
The cirular icon (3th from left) is now the icon for the app itself flameshot.svg.

Would be great if you could include a flameshot-tray.svg so we can change them later with different icon themes.
Thanks for this nice application

![trayicon](https://user-images.githubusercontent.com/10594806/50989584-10fa2600-1510-11e9-82b3-55022796209f.jpg)

**Comment by AlfredoRamos** [comment]
Which version are you using?

Since version [0.6.0](https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0) your theme can customize the tray icon with a file called `flameshot-tray`.

Make sure your theme includes a file with that name and you're using an updated version of Flameshot.

It's related to #366

**Comment by erikdubois** [comment]
On ArchLinux we can install 0.6.0-2 and have a git version.

I have placed flameshot-tray in different folders and recreated the icon cache each time.

I get no result.

In what folder does it need to be to work.

.
├── 16
│   ├── actions
│   ├── apps
│   ├── devices
│   ├── panel
│   ├── places
│   └── status
├── 22
│   ├── apps
│   ├── panel
│   ├── places
│   └── status
├── 24
│   ├── actions
│   ├── apps
│   ├── panel
│   ├── places
│   └── status
├── 32
│   └── places
├── 48
│   └── categories
└── scalable
    ├── actions
    ├── animations
    ├── apps
    ├── categories
    ├── devices
    ├── emblems
    ├── mimetypes
    ├── notifications
    ├── panel
    ├── places
    └── status

**Comment by AlfredoRamos** [comment]
I think it should be placed inside `panel`, or at least that's where the Papirus icon theme, which is the one I installed to test, place that file.

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/f8bc341fe1412c6c11bf97695564185f545ecd9f

On a side note, I'm not too familiar with theme creation, but shouldn't the directories below `scalable` be inside imside it instead?

**Comment by erikdubois** [comment]
![papirus-flameshot](https://user-images.githubusercontent.com/10594806/51461747-346a6f80-1d5f-11e9-804b-317c4dddb8b0.png)

can you install papirus and see if you are getting their tray icon?

**Comment by AlfredoRamos** [comment]
Yes, it shows me the tray icon, though I was using a light theme and I showed me the Light variant.

![flameshot_papirus_dark](https://user-images.githubusercontent.com/4165935/51493802-15c6a180-1d7c-11e9-95a4-57933963c906.png)

**Comment by erikdubois** [comment]
stays unresolved
will figure it out eventually
