### ISSUE TITLE
Allow colons in filenames

### ISSUE THREAD

**Issue by tastytea** [lupoDharkael/flameshot#447]
Colons are currently converted to `-` in filenames. Without colons it is impossible to construct a valid [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Times) time string.

**Comment by tastytea** [comment]
The replacement happens in `src/utils/filenamehandler.cpp`:

https://github.com/lupoDharkael/flameshot/blob/ee2f583acd425a9f35187c4eb17cbf1b993b4f36/src/utils/filenamehandler.cpp#L48

I believe this is because of macOS? One possible solution would be to replace `:` with "Unicode Character 'RATIO' (U+2236)" (`∶`). Another would be to only replace colons if the OS is macOS.

**Comment by Rmano** [comment]
Colons (`:`) are not valid in file names in all FAT-derived filesystems --- for example, Windows o FAT-32 memory sticks or whatever. See for example https://docs.microsoft.com/es-es/windows/desktop/FileIO/naming-a-file#file_and_directory_names

It is important especially for autogenerated names and if the directory is on some kind of shared filesytem. I remember a problem with autogenerated backups with the colon for the hour:minutes separators that was not recorded if the current directory was a memory stick....

**Comment by tastytea** [comment]
As far as I know:
* These are the characters not allowed in Windows filenames: `ASCII NUL`, `<>:"/\|?*`
* These are the characters not allowed in macOS filenames: `ASCII NUL`, `/:`
* These are the characters not allowed in UNIX filenames: `ASCII NUL`, `/`

Blocking only `/` and `:` seems arbitrary to me. According to the [Readme](https://github.com/lupoDharkael/flameshot#installation) only Linux is supported.

I propose to show a warning if any of the mentioned characters is used, but leave the filename intact. I think most people will not store screenshots on Windows- or macOS-filesystems.

**Comment by Rmano** [comment]
I agree with you for human-input filenames; a warning would be the ideal thing.

For the automatically generated ones, *any* of the characters you mention in the post above should be avoided, for the principle of least surprise.

My screenshot directory is shared via Dropbox, and some of the people using them are on windows... and the files simply do not appear on the other side.

**Comment by Rmano** [comment]
Notice that there was even a bug report for this: see issue #295 (many people dual-boot their computers).

**Comment by tastytea** [comment]
Closing this issue since it's a duplicate.
