### ISSUE TITLE
Make copy to clipboard after double click capture area(and then close) configable.

### ISSUE THREAD

**Issue by missuor** [lupoDharkael/flameshot#451]
A similar function has been provided by the current software (Ctrl + C), but I think if you can achieve this function by mouse click will be more quickly

**Comment by hosiet** [comment]
I'm wondering if that's necessary; there is already an icon that provides same functionality (to copy to clipboard).

**Comment by missuor** [comment]
I use deepin screenshot now. thanks all the same.

**Comment by missuor** [comment]
I think you can also try this tool, I think it is very smooth.
