### ISSUE TITLE
Moving or resizing does not affect screenshot

### ISSUE THREAD

**Issue by s3r6** [lupoDharkael/flameshot#459]
**Flameshot version**
0.6.0

**Describe the bug**
Moving or resizing by `arrow` or `shift-arrow` keys does not affect screenshot saved or copied.

**To Reproduce**

1. Run `flameshot gui`, I do this by hotkey `shift-print`
1. Select an area 
1. Adjust area size with `arrow` or `shift-arrow` keys
1. Copy `ctrl-c` or save `ctrl-s` screenshot

Screenshot is saved as selected first at p.2 - no adjustment.

**Expected behavior**
Saved adjusted image area.

**System Information**
Ubuntu 18.04.1 Mate.

**Comment by hosiet** [comment]
I can reproduce it. Looks like a giant bug.
