### ISSUE TITLE
Wrong version from Ubuntu 18.04 ppa and missing text feature

### ISSUE THREAD

**Issue by DaVukovic** [lupoDharkael/flameshot#465]
**Flameshot version**

From the Ubuntu 18.04 ppa I got Flameshot 0.5.1-2 installed. Opening the Flameshot information shows something different. See:

![flameshot](https://user-images.githubusercontent.com/7235787/52538510-e18b4300-2d73-11e9-9a8e-2ea3ecdf94bb.png)

So I'm not in which way I'm should follow this issue template and I know how annoying ignoring an issue template can be ;)

**Describe the bug**

AFAICT (and I tried to search hard for it), there's no text-tool available on Ubuntu 18.04. I'm using Flameshot on Ubuntu 16.04 and the text-tool is available there. But no matter what I do, I can't find it using Flameshot on Ubuntu 18.04 installed from PPA. Even the configuration doesn't show anything I might be able to enable. 

![flame2](https://user-images.githubusercontent.com/7235787/52538565-81e16780-2d74-11e9-96ba-7cd02cdeb305.png)
![flame3](https://user-images.githubusercontent.com/7235787/52538566-81e16780-2d74-11e9-9109-64dcc2fc6e1f.png)

any hint is welcome ;)

And thanks in advance.

**System Information**

```
davu@davu-Laptop-E-series:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
davu@davu-Laptop-E-series:~$ 
```

**Comment by ZetaoYang** [comment]
@DaVukovic try https://github.com/lupoDharkael/flameshot#installation  opensuse software repository.

**Comment by nettum** [comment]
Do you know if 0.6.x be released for bionic beaver on the official ubuntu repo?  
As mentioned I see I can download a .deb from the Opensuse repo that is 0.6.0.

**Comment by DaVukovic** [comment]
@ZetaoYang 

Thanks for you answer. Funnily enough, I have version 5.0.182-g337aef4 installed on 16.04 (I compiled that some time ago) and that already had the text feature. 

![flame](https://user-images.githubusercontent.com/7235787/52582597-d268cb80-2e2d-11e9-8921-983b5b886509.png)

I have to admit that I haven't followed the full development and if the text feature was reverted for everything < v5 and if so I have to apologize for not noticing it. But I expected that a newer version would also have that feature. Hence I was happy to see that version at the ubuntu repos ;).

Anyway. Thanks. I'll purge the Ubuntu ppa version and will compile from source. 

Issue can be closed

**Comment by ZetaoYang** [comment]
@DaVukovic You can close this issue.

**Comment by matiaso** [comment]
I had the same issue, I deleted the config file and relaunched it and both appeared. Config file is located there: 
> .config/Dharkael/flameshot.ini

**Comment by Jackiexiao** [comment]
> But I expected that a newer version would also have that feature. Hence I was happy to see that version at the ubuntu repos ;).

hope too

**Comment by Jackiexiao** [comment]
```
sudo apt remove flameshot
sudo apt install g++ build-essential qt5-default qt5-qmake qttools5-dev-tools
sudo apt install libqt5dbus5 libqt5network5 libqt5core5a libqt5widgets5 libqt5gui5 libqt5svg5-dev
sudo apt install git openssl ca-certificates
git clone https://github.com/lupoDharkael/flameshot.git
cd flameshot
mkdir build
cd build
qmake ../
sudo make
sudo make install
```

**Comment by billyjbryant** [comment]
This is a bandaid, not a fix. This issue should be re-opened @DaVukovic as the version in the Debian and Ubuntu repos are not up to date, is there any way to push this?

**Comment by maurizio-omissoni** [comment]
@Jackiexiao, thank you, best way to have the last and working flameshot with text
