### ISSUE TITLE
Error during Installation (libapache2-mod-php7.2)

### ISSUE THREAD

**Issue by Ahmeed2m** [lupoDharkael/flameshot#471]
**Flameshot version**
0.6.0-5

**Describe the bug**
While Installing it's all good until it can't setup libapache2 something due to environment path thing

> Unpacking flameshot (0.6.0-5) ...
> Processing triggers for mime-support (3.60ubuntu1) ...
> Processing triggers for desktop-file-utils (0.23-3ubuntu3) ...
> Processing triggers for man-db (2.8.4-2) ...
> Processing triggers for gnome-menus (3.13.3-11ubuntu2) ...
> Setting up libapache2-mod-php7.2 (7.2.15-0ubuntu0.18.10.1) ...
> /var/lib/dpkg/info/libapache2-mod-php7.2.postinst: 16: /etc/apache2/envvars: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin: not found
> dpkg: error processing package libapache2-mod-php7.2 (--configure):
>  installed libapache2-mod-php7.2 package post-installation script subprocess returned error exit status 127
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Setting up flameshot (0.6.0-5) ...
> Errors were encountered while processing:
>  libapache2-mod-php7.2
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 

**To Reproduce**
I don't know? I just ran 
`sudo apt install flameshot `
and idk if it helps or not the only thing I have installed related to php is lampp (php development application bundled with a version of php)

**Expected behavior**
to install without errors

**System Information**
KUbuntu 18.10

**Comment by hosiet** [comment]
It has absolutely nothing to do with flameshot. Please report the bug to Ubuntu against package libapache2-mod-php7.2;
