### ISSUE TITLE
I hope to add Chinese translation to this project

### ISSUE THREAD

**Issue by copie** [lupoDharkael/flameshot#48]
I am a Chinese, so I want to add a Chinese translation to this project
I hope to do something for this project
Thank you

**Comment by ZetaoYang** [comment]
Yes. It will be great.

Thank you.

To translate flameshot into Chinese you need perform the next few steps:

1. Download the archive with the source code of the program:
https://github.com/lupoDharkael/flameshot/archive/master.zip
2. Download Qt Linguist using this link:
https://github.com/thurask/Qt-Linguist/releases/download/20171103/linguist.exe
3. Open file `Internationalization_es.ts` in Qt Linguist, translate all phrases in its interface and save as `Internationalization_zh-cn.ts`. (For Traditional Chinese, the file name is `Internationalization_zh-hk.ts` or `Internationalization_zh-tw.ts`)
4. Then pull request.

**Comment by copie** [comment]
Okay, I am starting to work now

**Comment by lupoDharkael** [comment]
#52 merged

**Comment by lupoDharkael** [comment]
And thanks for the contribution!
