### ISSUE TITLE
[Feature request] highlighter pen improvements

### ISSUE THREAD

**Issue by adasomg** [lupoDharkael/flameshot#485]
1) Allow for organic drawing with it rather than only straight lines (this would more naturally be toggleable while, say, holding shift) 

2) Right now the highlight is basically drawn onto the screenshot as a color with reduced opacity. This makes the text less readable.
In editing software like Photoshop you'd draw the highlight on a separate layer and set the blending mode to 'multiply'  so that the (usually black/dark on white) text remains crisp while the background gets highlighted. QPainter seems to support blending modes.

**Comment by magnus-gross** [comment]
For 1.: You can already do freehand drawing with the very first tool (The pencil)
