### ISSUE TITLE
"Unable to capture screen" error on running flameshot commands

### ISSUE THREAD

**Issue by MichaelAquilina** [lupoDharkael/flameshot#487]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.12.0

**Describe the bug**
Running any of the flameshot commands e.g. `flameshot gui` quit immediately.

In the case of `flameshot` on it's own, I get the following error:

```
Qt: Session management error: Could not open network socket
```

For others like `flameshot full` and `flameshot gui` I get a notification with the message:

`Unable to capture screen`

**To Reproduce**
Run `flameshot` or `flameshot gui` in the terminal

**Expected behavior**
flameshot will launch

**System Information**
OpenSUSE Tumbleweed
i3 window manager

**Comment by MichaelAquilina** [comment]
Update: seems like running `unset SESSION_MANAGER` solved the qt management error problem. But I still get the notifications telling me flameshot was unable to capture the screen when running other commands.

**Comment by MichaelAquilina** [comment]
This seems to work on my other machine with the exact same configuration. So not entirely sure what is going on :/

**Comment by MichaelAquilina** [comment]
Since reporting this issue, I've managed to solve this issue - but not entirely sure how. I suspect my session was in a weird state so I am just going to mark this issue as resolved to make the issues backlog cleaner.

**Comment by AmaralMarti** [comment]
Me too.

**Comment by JohnNiang** [comment]
I've face the same issue.

**Environment**

```shell
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

It only happens when I switch my **Desktop Environment** from Gnome into i3wm.

**Comment by mmahmoudian** [comment]
@JohnNiang @AmaralMarti @qianyigengwu considering that you didn't provide your system information, there is not much we can do. If you are using a tiling window manager, most probably you are either missing systray ([explained briefly here](https://flameshot.org/guide/faq/#flameshot-doesnt-start-no-tray-icon)) or the notification daemon:
Try `notify-send "teeeest"` and if you don't see the notification try installing `dunst` or something similar.

If you still had issues, open a new issue on this gitub repo, but before that try searching in open and closed issues to prevent creation of duplicated posts.

**Comment by JohnNiang** [comment]
@mmahmoudian 

**System info** as follow:

```shell

 ██████████████████  ████████     johnniang@x1c
 ██████████████████  ████████     OS: Manjaro 21.0.5 Ornara
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.36-2-MANJARO
 ██████████████████  ████████     Uptime: 6h 2m
 ████████            ████████     Packages: 1551
 ████████  ████████  ████████     Shell: zsh 5.8
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     WM: i3
 ████████  ████████  ████████     GTK Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Dark
 ████████  ████████  ████████     Font: Noto Sans 10
 ████████  ████████  ████████     Disk: 66G / 1.5T (5%)
 ████████  ████████  ████████     CPU: 11th Gen Intel Core i7-1165G7 @ 8x 4.7GHz [57.0°C]
 ████████  ████████  ████████     GPU: Mesa Intel(R) Xe Graphics (TGL GT2)
                                  RAM: 7536MiB / 31833MiB
```

**Comment by mmahmoudian** [comment]
@JohnNiang So does Flameshot works now for you (after installation of `dunst`)?

**Comment by JohnNiang** [comment]
@mmahmoudian Not yet. I've installed dunst before Flameshot went wrong.

**Comment by mmahmoudian** [comment]
@JohnNiang Do you have systray? I mean, do you see Flameshot icon in the tray area?

**Comment by JohnNiang** [comment]
> @JohnNiang Do you have systray? I mean, do you see Flameshot icon in the tray area?

Yup, I confirm that systray is working well and Flameshot icon is staying in the tray area.

**Comment by mmahmoudian** [comment]
@JohnNiang try the following

1. open two terminals
2. in the first one type:
    > ```sh
    > pkill flameshot ; sleep 1s ; flameshot
    > ```
3. in the second one try
    > ```sh
    > flameshot gui
    > ```

Then post the content of each terminal here.

**Comment by JohnNiang** [comment]
**Left:**

```bash
➜  ~ pkill flameshot ; sleep 1s ; flameshot
Qt: Session management error: Could not open network socket
QSettings::value: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
QSettings::value: Empty key passed
QSettings::setValue: Empty key passed
```

**Right**

Flameshot works very well now.

Thanks a lot for your patient instructions.

**Comment by JohnNiang** [comment]
@mmahmoudian 

![image](https://user-images.githubusercontent.com/16865714/120624760-942ac680-c493-11eb-8258-b47f12a5a71a.png)

But If I kill left `flameshot` process and execute `flameshot gui`, it gose wrong again.

**Comment by mmahmoudian** [comment]
@JohnNiang check if dbus is running:

![image](https://user-images.githubusercontent.com/390889/120626192-16eb5b80-c46b-11eb-8fa7-574257acbf5f.png)

**Comment by mmahmoudian** [comment]
@JohnNiang So you mean when the left `flameshot` is running, then the `flameshot gui` works correctly? if so, this is because it should work that way. Flameshot should be in you tray area when you want to take screenshot.

**Comment by JohnNiang** [comment]
> @JohnNiang So you mean when the left `flameshot` is running, then the `flameshot gui` works correctly? if so, this is because it should work that way. Flameshot should be in you tray area when you want to take screenshot.

If I executed `flameshot gui` only, the Flameshot icon appeared in my tray area, and `Unable to capture screen` notification popped up.

**One thing we have to notice: It only happens when I switch my Desktop Environment from Gnome to i3wm.**
