### ISSUE TITLE
[feature request] make the screenshot stick on the screen

### ISSUE THREAD

**Issue by zcqzcg** [lupoDharkael/flameshot#513]
Flameshot is the best screenshot software on Unbuntu, thanks for your effort!

As the title said: I would like to suggest a new feature as -- make the screenshot stick on the top level of the screen.

For example: I have searched some tutorial online, and when I start to follow the tutorail, I'll have to change the window between my working-window and the chrome-window. And it's just terrible.

So what if I can just make it a screenshot, which will float on the top level of the screen, so I can get to work without changing windows.

If this feature could be added, you will save my life from changing windows for good.

Thanks !

**Comment by ZetaoYang** [comment]
@zcqzcg Try flameshot `Pin` tool. It can pin the screenshots onto the top of window.

**Comment by zcqzcg** [comment]
Thanks, it works!
