### ISSUE TITLE
Flameshot buttons have no icons

### ISSUE THREAD

**Issue by rstrube** [lupoDharkael/flameshot#535]
**Flameshot version**
0.6.0-9 (Debian)

**Describe the bug**
When capturing from the screen, most of the buttons are not displaying icons, just round purple buttons.

**To Reproduce**
Initiate a screen capture.

**Expected behavior**
The buttons should have icons.

**System Information**
Pop_OS 19.04 (Ubuntu 19.04 based).

![Screenshot from 2019-05-16 11-14-56](https://user-images.githubusercontent.com/4212764/57873742-3bb0ff80-77cc-11e9-8e50-2461fa3c2fdd.png)

**Comment by rstrube** [comment]
Perhaps I need to install a specific font?

**Comment by hosiet** [comment]
Can you confirm that you already have package libqt5svg5 installed?

**Comment by rstrube** [comment]
That did it! I guess Pop_OS doesn't have that package installed by default, but regular Ubuntu 19.04 does.  The icons are now appearing.

**Comment by CurtisBelt** [comment]
Appreciate you guys, had the same issue on Fedora 30.

Solution:

```
sudo dnf install qt5-qtsvg
```

Then reboot or `killall flameshot`

**Comment by saurabh000345** [comment]
I'm facing the same problem in Arch Linux. I have installed the package qt5-svg. But the icons still don't appear.

**Comment by farseerfc** [comment]
@saurabh000345  the `qt5-svg` package should be a hard dependency for the `flameshot` package. May I ask how did you installed flameshot without qt5-svg on Arch Linux? Also have you tried to kill and restart flameshot after (somehow) installed `qt5-svg` ?

**Comment by saurabh000345** [comment]
@farseerfc I tried the AUR package `flameshot` and also `flameshot-git`. I later discovered a pacman package too. But all of them gave me the same result.Screenshots are taken fine, the freehand drawing tool works fine, but the buttons don't have any icon. That led me to this thread which suggested that I should install `libqt5svg` and I guess qt5-svg is the package for Arch systems. And yeah as you said that qt5-svg is a hard-dependency, the package was already installed. I would still try updating the system and giving you a feedback soon. But if you have any other suggestions, do help me with the issue.

**Comment by saurabh000345** [comment]
@farseerfc Yeah the update doesn't change a thing.

**Comment by romber** [comment]
Same issue in Kubuntu 14.04:

**flameshot version**
`v0.6.0 flameshot_0.6.0_x86_64.AppImage`

**libqt5svg5 version**
`libqt5svg5:amd64 5.2.1-1`
