### ISSUE TITLE
Text cannot be entered in Chinese

### ISSUE THREAD

**Issue by imaojun** [lupoDharkael/flameshot#562]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.12.1

**Describe the bug**
 Text cannot be entered in Chinese.
My input method tray icon has been switched to Chinese input method. But I can't input Chinese, and I can't switch input method when using TEXT,only English letters can be entered.

![Peek 2019-06-21 13-27](https://user-images.githubusercontent.com/28778042/59899773-87d50c80-9428-11e9-800b-c6e4d475a3a4.gif)

**To Reproduce**
I use pamcan as my package management tool and use the fcitx-rime input tool.
```sh
# intall input tool
$ sudo pacman -S fcitx-rime
$ sudo pacman -S fcitx-configtool
```
Install the Simplified Chinese input method in the input tool.
Switch to Chinese input status and enter Chinese in the flameshot use TEXT function.

**Expected behavior**
When using the TEXT function, Chinese can be input in Chinese input tool.

**System Information**
4.19.49-1-MANJARO

**Comment by hosiet** [comment]
For my testing on Debian 10, Chinese characters can be typed in but the character selection box will not show up anyway.

**Comment by imaojun** [comment]
@hosiet testing on Archlinux or Manjaro it does not work.But I thought of an alternative, first enter the content and copy the clipboard, copyq will store them. When I use the Text function, I use the global shortcut to copy the contents of copyq (you can select the previous/next content), and then paste it with ctrl-v and it will be perfect. The downside is that I have to think about what I need in advance when I need to use the TEXT feature. However, it is much more convenient than opening screenshot in other software and adding text.
![Peek 2019-07-31 09-28](https://user-images.githubusercontent.com/28778042/62176994-e8376200-b375-11e9-9ee1-e693fdc3d597.gif)

**Comment by imaojun** [comment]
solved.In addition to the following configuration：
```sh
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
```

Need additional installation of the fcitx-qt module.Add the fcitx-qt5 module method in archlinux:
```sh
$ sudo pacman -S fcitx-qt5
```

Restart the fcitx input tool and flameshot after installation. Then try Chinese input. success.

**Comment by amosbird** [comment]
> solved.In addition to the following configuration：
> 
> ```shell
> export XMODIFIERS=@im=fcitx
> export GTK_IM_MODULE=fcitx
> export QT_IM_MODULE=fcitx
> ```
> 
> Need additional installation of the fcitx-qt module.Add the fcitx-qt5 module method in archlinux:
> 
> ```shell
> $ sudo pacman -S fcitx-qt5
> ```
> 
> Restart the fcitx input tool and flameshot after installation. Then try Chinese input. success.

It still doesn't work for me.

**Comment by exploman** [comment]
@maojunxyz 你好，楼主。解决不能输入中文，是不是只能自己编译
