### ISSUE TITLE
Options around snapshotted area lacking icons.

### ISSUE THREAD

**Issue by brianjmurrell** [lupoDharkael/flameshot#568]
**Flameshot version**
0.6.0

**Describe the bug**
Options around snapshotted area lacking icons.

**To Reproduce**
Take snapshot.

**Expected behavior**
Circles should have icons in them.

**System Information**
Fedora 30

![image](https://user-images.githubusercontent.com/559317/60015833-6f483a80-9652-11e9-80cc-8e5f28afb95a.png)

**Comment by CurtisBelt** [comment]
@brianjmurrell 

Found the answer here: https://github.com/lupoDharkael/flameshot/issues/535

Solution:

```
sudo dnf install qt5-qtsvg
```

Then reboot or `killall flameshot`

**Comment by brianjmurrell** [comment]
Cheers!

Duplicate of #535.
