### ISSUE TITLE
Unable to open the right click menu in chromium after a screenshot

### ISSUE THREAD

**Issue by mssdvd** [lupoDharkael/flameshot#58]
OS: Arch Linux
WM: i3
flameshot: latest

I can't open the right click menu in chromium after a flameshot session. The only way to make work again the button is to focus another window. Chrome/Chromium seems to be the only program with this issue.

**Comment by lupoDharkael** [comment]
Looks like a problem of the window manager more like a problem of the program itself.
Anyway, I'll ask a friend who uses i3 if he can reproduce the issue.

**Comment by mssdvd** [comment]
Ok thanks.

**Comment by mssdvd** [comment]
The menu button doesn't work too

**Comment by lupoDharkael** [comment]
My friend tested it and seems to happen in his system too.
I think this should be reported to i3.

Here are the flags of the capture widget: https://github.com/lupoDharkael/flameshot/blob/68df636d187d7aed51817c1c431c2e86623ba453/src/capture/widget/capturewidget.cpp#L80
After the creation of the widget it is shown in fullscreen mode.

Hope this helps for the report. I suspect that is the cause of the problem (the instantiation of the widget in full screen mode).

**Comment by mssdvd** [comment]
Ok thank you. I'll report it to i3.

**Comment by mssdvd** [comment]
Resolved in https://github.com/i3/i3/pull/3097/commits/a06e66982bc921d05b68b75f8e12323c284233d0
