### ISSUE TITLE
Box-drawing border thickness is wildly inconsistent across systems

### ISSUE THREAD

**Issue by sgbeal** [lupoDharkael/flameshot#589]
**Flameshot version**
Unknown - it's not shown in the UI. It's whatever Linux Mint 19.2 uses.

**Describe the bug**
The line width of the box drawing tools is extremely inconsistent. i have 2 Mint 19.2 systems, one which draws fine lines and one which draws unusably thick ones, and i have no idea why one system draws thick lines.

**To Reproduce**
This appears to be system specific:

![image](https://user-images.githubusercontent.com/235303/62829783-50513800-bc01-11e9-8632-1ba4e22c5ca2.png)

That line thickness is okay for that example use, but in many cases it's far too thick, blocking out content i want to show. On my laptop, with the same OS/package versions, it draws a comfortably thin line.

**Expected behavior**
i expected the thickness to be consistent across systems (and not huge) and/or to have a configuration option to tweak it.

**System Information**
Mint Linux 19.2 on two separate computers.

# AHA - there is a setting, but not in the UI

While writing this ticket i tried, out of desperation, to export the config and see if there was a setting in there. Indeed...

    cat ~/tmp/flameshot.conf
    drawThickness=11

i've never export/imported the config before, so why it's set so thick here is unknown. After changing it to 4 (presumably pixels) and importing it, the line thickness is reasonable:

![image](https://user-images.githubusercontent.com/235303/62829810-e38a6d80-bc01-11e9-901a-b11b5f91d9a6.png)

i'm going to post this ticket anyway (and will close it immediately afterwards) in the hopes of saving another use some grief.

**Comment by sgbeal** [comment]
Closing - see explanation near the bottom of the report.

**Comment by hosiet** [comment]
I feel sorry for users keep ignoring the startup information, which actually says:

> Press Enter to capture the screen.
> Press Right Click to show the color picker.
> Use the Mouse Wheel to change the **thickness of your tool**. (<-- read this sentence please)
> Press Space to open the side panel.

Those words for usage pop up every time you enter the capture mode. However, that's also the reason why users keep ignoring it. Not your fault @sgbeal , I just want to let you know that it can be elegantly configured.

**Comment by sgbeal** [comment]
i appreciate you pointing that out, but an unintuitive misuse of the mouse wheel is anything but elegant. If the mouse wheel is the proper way to change this, it should arguably not be persistent when changed that way. i apparently changed it by accident and was annoyed by thick lines for the next several dozens screenshots.

**Comment by sgbeal** [comment]
Showing people a "wall of text" when they're trying to get something done is the best way to get people to ignore that text. Help text should, IMO, be shown only when a user goes looking for it, not when a user is trying to get something done. That's why we all click through license agreements and "this site uses cookies, select your options" dialogs - because we didn't go looking for that, we went looking for something else and that dialog is in our way, distracting us from our current purpose. In the case of the flameshot text, it very often literally blocks what we're trying to mark. That's possibly intentional, to try to force us to read it, but when someone is in the mindset of taking a screenshot, anything on the screen which is in their way is just a distraction.

**Comment by Dinduks** [comment]
@sgbeal Not mentioning that on high DPI screen, the text is so small you don't even want to try to read it!

Thank you @hosietI for feeling sorry for us! So empathetic of you.

Dharkael thank you for creating this amazing tool!

**Comment by srosato** [comment]
Came here only to realize I didn't read the popup either. So we are part to blame as well for not reading, but yeah, when I take a screenshot, any wall of text that I see is just automatically dismissed by me because I wanted to get my screenshot done and in this world of too much notifications, I just ignored it :/

**Comment by karlhorky** [comment]
Yeah I also just came to find this here, I also didn't read the text that appeared when I was trying to quickly take a screenshot to send to a colleague.

I did, however search in the Flameshot configuration settings and didn't find anything.

Maybe it would be something to consider to add controls in the configuration settings for this?

cc @lupoDharkael @borgmanJeremy @ZetaoYang

**Comment by mmahmoudian** [comment]
@karlhorky What version are you using? If I don't make mistake, we added two buttons from v0.9.0 (disabled by default but can be enabled via GUI settings window) to show two buttons: A <kbd>+</kbd> and a <kbd>-</kbd> to chabge the thickness. Additionally you can press <kbd>SpaceBar</kbd> to open the sidebar and change the thickness with the slider.

**Comment by karlhorky** [comment]
Ah ok nice, maybe enable them by default too? Or, what was the thinking there with disabled by default?

**Comment by mmahmoudian** [comment]
@karlhorky they will not be enabled (at least for the time being) as we already have many buttons enables and more buttons will clutter the UI. We already got some feedback from users that the UI looks "too busy". The important thing is that there are 3 distinct way implemented to change the thickness. Perhaps more efforts should be directed towards informing/educating users either through documentation, tutorial videos or some in-app daily tips and tricks. For the first two, any help/contribution is very very appreciated. As for the latter, a feature request is already in place.

**Comment by karlhorky** [comment]
Ok, just thinking that there may be ways to make these 3 ways more naturally discoverable :) Eg. I really like tools like Figma, which have a ton of features, but which are also naturally discoverable without being to cluttered. But this would also be a not so insignificant effort to get there, I suppose

**Comment by j1v37u2k3y** [comment]
Couldn't you just have an option for the default rectangular width in the options section?

**Comment by j1v37u2k3y** [comment]
Or it seems I might have adjusted it enough to set it to default a better width.. Not sure how I made it work but maybe just by sliding and moving the slider until it started working ¯\_(ツ)_/¯.
