### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by tjgruber** [lupoDharkael/flameshot#59]
First of all, this is the most awesome tool ever!  Excellent work!

Not necessarily an issue, but lack of experience on my part:

As you release new versions and updates, how do I update this?

Do I just re-download and install? Must I uninstall it first?  Is there an update process?

How do I uninstall?  Do I run "make uninstall" from the directory I made it from?

I'm running it on Fedora 27 Workstation in Gnome 3.26.

Thank you!

**Comment by lupoDharkael** [comment]
if you are updating from an older version you can just `make install` and all the files will be replaced.
If you need to delete them from your system `make uninstall` will do the work for you :)

I know this is not convenient but please, be pacient while we work on having packages for the main distros.
