### ISSUE TITLE
How to make flameshot default screenshot tool on Deepin 15.11

### ISSUE THREAD

**Issue by Tset-Noitamotua** [lupoDharkael/flameshot#602]
In [Deepin Desktop 15.11](https://www.deepin.org/en/) (Debian based Linux distro) screenshot shortcuts are tight to their native tool.

Installation of Flameshot with `sudo apt install flameshot` works out of the box. But how to make Flameshot the default screenshot tool?

This are Deepin's default keyboard shortcuts for screenshots:
![image](https://user-images.githubusercontent.com/5635462/64177204-4ec10b80-ce5f-11e9-8da0-28d51fc76a10.png)

**Comment by jam-2000** [comment]
@Tset-Noitamotua
You can set your own shortcut.
keyboard > shortcut > find at the end CUSTOM SHORTCUTS

set name "my screenshotter", set command "flameshot gui", set shortcut (for example press PrintScreen button)
agree with warning about already existed shortcut (simply ADD)
also check in flameshot's settings checkbox "start at system startup" and, if you want, check "don't display icon in system tray"
and that's it, you have your own screenshotter with your own desired shortcut
