### ISSUE TITLE
After copy to clipboard, it takes 50 seconds to come back

### ISSUE THREAD

**Issue by Kukulkano** [lupoDharkael/flameshot#607]
**Flameshot version**
0.6.0-36 compiled with QT 5.11.1

**Describe the bug**
I make a screenshot, eg with annotations, and after clicking the "copy to clipboard" button, the GUI freezes for about 50 seconds. The state is exactly as while clicking the button, showing dimmed screen and markers around the area I have chosen. After waiting for 50 sec, it comes back and continues with image in clipboard. No idea why this happens. System restarted, installed most recent flameshot, still the same.
No problem if I save the screenshot or cancel using ESC key. No other issues with clipboard so far.

If I execute **dunst** somewhere, it returns immediately. Sadly, it does not show anything. If dunst is not running, it takes 50 seconds.

What can I do?

**System Information**
KDE Neon with Ubuntu 16.04 LTS backend.

**Comment by Kukulkano** [comment]
Seems duplicate of #353

**Comment by emielvanberlo** [comment]
I use XFCE but had some KDE traces left.
my notifications didn't work.
remove plasma-workspace fixed my notifications and flameshot.
