### ISSUE TITLE
linux for Ubuntu

### ISSUE THREAD

**Issue by Suremotoo** [lupoDharkael/flameshot#61]
Can i use it on Ubuntu ？   my os ：Ubuntu 16.04 LTS

**Comment by ZetaoYang** [comment]
Yes, of course.

**Comment by omkarnathsingh** [comment]
Yes. Its working for Ubuntu. I built it from debian steps.

**Comment by alexanderadam** [comment]
I just want to mention that [there is also a PPA by @nemonein:](https://github.com/lupoDharkael/flameshot/issues/46#issuecomment-357135969)

`sudo add-apt-ppa ppa:nemonein/tailored`
https://launchpad.net/~nemonein/+archive/ubuntu/tailored
