### ISSUE TITLE
Text writing feature

### ISSUE THREAD

**Issue by nikesptg** [lupoDharkael/flameshot#616]
Hi guys!

I am a relatively new LInux user and in my windows times I used a Lightshot
https://www.facebook.com/Lighshot

Your tool is much better and I just love it. However, I do miss a feature of text commenting.
It is very useful and in many cases crucial 

Do you think you can add it to your app?

thanks in advance

Nick

**Comment by DesertStars** [comment]
This feature exists, it was added in v0.6.0.

https://github.com/lupoDharkael/flameshot/releases/tag/v0.6.0

See ''Add Text tool.'' part. If your flameshot is older than this version you should update or wait for your distro's package manager to update to v0.6.0.

**Comment by nikesptg** [comment]
thank you! just updated. Works great!!!
