### ISSUE TITLE
Flameshot add suggestion

### ISSUE THREAD

**Issue by ramzydoni** [lupoDharkael/flameshot#62]
thank's for this great softawre 
i want to add a small tool that is flou
Thanks in advance
exmple
https://i.imgur.com/qewVNPX.png

**Comment by mimecry** [comment]
if you're talking about the Blur tool, Flameshot already has it, although you have to enable it in the settings. 

I do agree that the current Blur tool is not sufficiently blurry, you can still make out the text in many cases

http://i.imgur.com/jtu8d4M.png

**Comment by pemartins1** [comment]
This is one of those must have apps, congrats to the developers!

Let me give some suggestions I would find very useful for myself:

- Copy to clipboard (without the need to upload to imgur first);
- Text tool (something simple with text orientation, size and colour);
- imgur login option (to upload images directly to our user accounts).

**Comment by sajidzaman** [comment]
+1 for the Text Tool, Text Tool would make it complete.

**Comment by b4ssrp** [comment]
@pemartins1 
![image](https://user-images.githubusercontent.com/28487930/34764031-332584ea-f5fe-11e7-9e48-911a4ce09da5.png)

For fullscreen capture you can use `flameshot full`, it's getting saved to path defined in `flameshot config`, to copy fullscreen capture to clipboard use `flameshot full -c`

**Comment by lupoDharkael** [comment]
@sajidzaman https://github.com/lupoDharkael/flameshot/issues/11

I plan to implement configurable shortcuts inside the gui mode with the posibility of assigning multiple actions to a single shortcut. That would solve the problem of copy+save and others.

**Comment by AlfredoRamos** [comment]
I just installed this application and I'm liking it so far, however being able to upload images to an Imgur account would be a good feature to add.

I'm migrating from another screenshot application and that's the only feature I really miss.

**Comment by vendforce** [comment]
@mimecry
the blur tool works great you can just go over it twice and its completely blurred out

**Comment by giedriusStan** [comment]
I am only missing two features: 
Text tool and ability to move arrows after they been drawn

**Comment by mimecry** [comment]
@vendforce ah why didn't i think of that.. doesn't have the 'cleanest' look, but works very well otherwise.

**Comment by lupoDharkael** [comment]
I'm closing this issue as it's hard to keep track of it, feature request should be in separated issues, and I think every suggestion here have been implemented/reported in other issues.
