### ISSUE TITLE
Configure brush size

### ISSUE THREAD

**Issue by rgarrigue** [lupoDharkael/flameshot#634]
Hi

When I want to draw on the screenshot, the arrow, line etc are too big. 

![image](https://user-images.githubusercontent.com/1872031/66847440-a9c44300-ef73-11e9-9d4d-4f5fd0550acd.png)

Maybe it's because I've a high resolution (3440x1440) ? 

Anyway I'ld like to be able to reduce it.

& thanks for the great software :-) :+1:

**Comment by hosiet** [comment]
Please use your mouse wheel to adjust the brush value.

**Comment by rgarrigue** [comment]
Oh... ah... hehe well good ! Maybe a tooltip on the topic would help peoples. But fine for me ! :)

**Comment by HKalbasi** [comment]
Is there any alternative or keyboard shortcut? For people with mouse pad or broken mouse wheel.

**Comment by mmahmoudian** [comment]
@HKalbasi  By pressing <kbd>space bar</kbd> or by clicking on the button on the left hand side of your monitor you can open the "Tool Settings" menu and from the top slider you can configure the thickness. You can in fact change all the settings for the selected tool in that sidebar.

There are of course other methods in development (e.g #1131) to make Flameshot even useful for tablets. But for those you have to wait until it is fully merged in.
