### ISSUE TITLE
Permission denied?

### ISSUE THREAD

**Issue by Kymus** [lupoDharkael/flameshot#65]
Sorry if this is a captain obvious issue; I'm not super great at compiling from source.

I followed the readme's directions, and then near the end:

 ```
kymus@Sanxing:~/flameshot$ sudo qmake && make
Updating '/home/kymus/flameshot/translation/Internationalization_es.qm'...
Removing translations equal to source text in '/home/kymus/flameshot/translation/Internationalization_es.qm'...
    Generated 133 translation(s) (133 finished and 0 unfinished)
Updating '/home/kymus/flameshot/translation/Internationalization_ca.qm'...
Removing translations equal to source text in '/home/kymus/flameshot/translation/Internationalization_ca.qm'...
    Generated 132 translation(s) (132 finished and 0 unfinished)
Updating '/home/kymus/flameshot/translation/Internationalization_ru.qm'...
Removing translations equal to source text in '/home/kymus/flameshot/translation/Internationalization_ru.qm'...
    Generated 134 translation(s) (0 finished and 134 unfinished)
    Ignored 3 untranslated source text(s)
Updating '/home/kymus/flameshot/translation/Internationalization_zh-cn.qm'...
Removing translations equal to source text in '/home/kymus/flameshot/translation/Internationalization_zh-cn.qm'...
    Generated 131 translation(s) (129 finished and 2 unfinished)
    Ignored 4 untranslated source text(s)
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=\"v0.5.0-44-g4a11806\" -DQT_DEPRECATED_WARNINGS -DQAPPLICATION_CLASS=QApplication -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc/third-party/singleapplication -Isrc/third-party/Qt-Color-Widgets/src -Isrc/third-party/Qt-Color-Widgets/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o singleapplication.o src/third-party/singleapplication/singleapplication.cpp
Assembler messages:
Fatal error: can't create singleapplication.o: Permission denied
Makefile:1072: recipe for target 'singleapplication.o' failed
make: *** [singleapplication.o] Error 2
kymus@Sanxing:~/flameshot$ 
```

 
I used the _sudo_ command but I'm getting a "permission denied" error and then the installation fails? 

I'm using Ubuntu 17.10 FWIW

**Comment by lupoDharkael** [comment]
You dont need to use `qmake` as root, remove the `sudo` and everything should compile.

**Comment by Kymus** [comment]
Thanks for the reply :).

When trying that, I get a new error:

`kymus@Sanxing:~/flameshot$ qmake && make
Updating '/home/kymus/flameshot/translation/Internationalization_es.qm'...
Removing translations equal to source text in '/home/kymus/flameshot/translation/Internationalization_es.qm'...
lrelease error: cannot create '/home/kymus/flameshot/translation/Internationalization_es.qm': Permission denied
Project ERROR: Failed to run: /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease -removeidentical translation/Internationalization_es.ts -qm /home/kymus/flameshot/translation/Internationalization_es.qm
`

**Comment by lupoDharkael** [comment]
as you run qmake with root you generate some files as root, then you can modify them with a non root user.You have to remove the file called Makefille and remove the files from ./translation with extension .qm

run this from the base directory of the project:
`sudo rm Makefile translation/*.qm`

And then just `qmake && make`. After the code compilation you can run `sudo make install` and it will have it installed in your system.
hope it helps :)

**Comment by Kymus** [comment]
Now I get this:

```
kymus@Sanxing:~/flameshot$  sudo rm Makefile translation/*.qm
[sudo] password for kymus: 
kymus@Sanxing:~/flameshot$ qmake && make
Updating '/home/kymus/flameshot/translation/Internationalization_es.qm'...
Removing translations equal to source text in '/home/kymus/flameshot/translation/Internationalization_es.qm'...
lrelease error: cannot create '/home/kymus/flameshot/translation/Internationalization_es.qm': Permission denied
Project ERROR: Failed to run: /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease -removeidentical translation/Internationalization_es.ts -qm /home/kymus/flameshot/translation/Internationalization_es.qm
```

:\

**Comment by lupoDharkael** [comment]
That's weird. Do you get the same error if you download the repo again and do a normal `qmake && make`?

**Comment by lupoDharkael** [comment]
I you can find a way you could try this .deb package:
[flameshot_ubuntu17_amd64.zip](https://github.com/lupoDharkael/flameshot/files/1610346/flameshot_ubuntu17_amd64.zip)

I'm sorry for the inconveniences, the project needs official packages as soon as possible in order to have a more user friendly installation.

**Comment by trmdi** [comment]
Try removing everything then start again.
```
$ rm -rf /home/kymus/flameshot
$ git clone...
$ qmake...
```

**Comment by krepver** [comment]
Usually qmake adds `distclean` target for make. It removes Makefile and so on. So `sudo make distclean` could help

**Comment by Kymus** [comment]
Thanks for the .deb package! Sorry I haven't updated this thread; I've been really busy and haven't felt like troubleshooting on my down time XD. 

It seem to run fine! I was able to launch it fine enough. Dumb question, though: how do edit my screenshot or otherwise make it "go"? The screenshot button does nothing. I read the documentation on the front page, and "$ flameshot gui" has the problem of there being a terminal in the way. There's something really obvious I'm missing here, right? Sorry >_<

**Comment by lupoDharkael** [comment]
you can tell your desktop to run the command after you press a key, the configuration is specific of your desktop environment.

**Comment by Kymus** [comment]
Got it, thank you!
