### ISSUE TITLE
Internationalization and keyboard shotcuts SHIFT 

### ISSUE THREAD

**Issue by linuxeng** [lupoDharkael/flameshot#66]
*Good Day*.
I assembled the program and ran into the fact that the path **/usr/share/flameshot/translations/** is constant. When compile with default prefix /usr/local. ,  
```
QTranslator translator;
    translator.load(QLocale::system().language(),
      "Internationalization", "_", "/usr/share/flameshot/translations/");
```
Because of this,  when compile with default prefix /usr/local the localization does not work and you have to manually create a link or copy translations into **/ usr / share /**.
See file **src/main.cpp**

### Shotcuts SHIFT to the righ. and SHIFT bottom does not work.

Best Regards.
Vadim K.
Russia.

**Comment by lupoDharkael** [comment]
Now translations use a fixed install path again. It should work as before while I rewrite it for windows and I implement non fixed paths in the code.

**Comment by lupoDharkael** [comment]
The shortcuts should work now.

**Comment by pafri** [comment]
Czech localization file. Attached, ready to be committed. Best regards. Pavel Fric
[Internationalization_cs.zip](https://github.com/lupoDharkael/flameshot/files/2728547/Internationalization_cs.zip)

**Comment by pafri** [comment]
Hi,
I thought, I made the "new issue". And I don´t realize, why it ended, where it is?
Best regards, Pavel Fric

    On Sunday, January 6, 2019, 5:24:39 PM GMT+1, Boyuan Yang <notifications@github.com> wrote:  
 
 
@pafri I guess you should provide it in the form of Pull Request or at least please open a new issue. It doesn't make sense to provide translation files in a totally irrelevant issue.
