### ISSUE TITLE
Pin, drag and zoom do not work

### ISSUE THREAD

**Issue by geekthought** [lupoDharkael/flameshot#661]
0.6.0+git20190714-1(Debian)

If i press pin after creating the screenshot, the pin is fixed to the left of my main monitor and cannot be dragged or zoomed properly. If i create another pin the screenshots are stacked at the same position and cannot be dragged or zoomed. 

Freely drag the pins around

Ubuntu 19.10

**Comment by ZetaoYang** [comment]
It's Wayland issue.
You can make all your QT apps use XWayland:
`export QT_QPA_PLATFORM=xcb`
Add this to `/etc/profile` file, then restart.
