### ISSUE TITLE
Systray option to invoke taking a screenshot

### ISSUE THREAD

**Issue by fatso83** [lupoDharkael/flameshot#672]
I am always frustrated when trying to use Flameshot after a long hiatus, because I use 5 minutes before I have found out how to take a screenshot! It is very far from a user friendly experience.

The systray icon is there, but clicking it just shows the options for configuration and info, not any action item. Opening either of those shows no hints of how to use the system either. Some guides on the net indicate that the systray icon has an option to take a screenshot, which makes one question whether the build is actually outdated or non-functional, as there is no such option. 
![2019-12-11__11_47_45_screenshot](https://user-images.githubusercontent.com/618076/70615117-13776b00-1c0c-11ea-8353-3ceffe6d8f3e.png)

I finally got this working _by chance_, as I double clicked the systray icon (a UX interaction which I have seen _no other app use_ and it also doesn't work in all UI states, like in a search). That finally invoked the screenshot command.

One article also pointed to a menu entry that would invoke this command. That seems a rather convulated way to do it, but after searching for flameshot I found one entry called "Take graphical screenshot", or "Take graphical ..." as it actually shows. Right clicking that and adding it to favorites finally made a pretty convenient one-click way of taking a screenshot!

While this works _in the end_, it would be nice if there was at least one simple way of invoking this command from the systray icon that did not have its basis in luck. Would you consider adding a third entry called "Take screenshot" to the menu?

![2019-12-11__11_41_10_screenshot](https://user-images.githubusercontent.com/618076/70614637-2ccbe780-1c0b-11ea-80e1-ee8cfb19046a.png)

**Comment by enolive** [comment]
which version of flameshot are you using? I started with 0.5x (which is installable from the ubuntu repo) which has the described behaviour. flameshot 0.6.0 includes the mentioned option in its systray menu.

**Comment by fatso83** [comment]
@enolive Aha, that's an improvement! I am indeed using 0.5.1-1 (Debian) from the Ubuntu repos. Version 0.6, installed using the snap package, fixed this.
