### ISSUE TITLE
not saving to file, however saving to clipboard 

### ISSUE THREAD

**Issue by qowai** [lupoDharkael/flameshot#728]
greetings ... 
first of all thank you for taking the time out of your life to create this truly awesome and useful tool 

i've been enjoying your program for a while now ... it's been working great on 2 laptops ... one fedora with no issues and one opensuse when just recently i'm having problems ... after pushing the "print screen" button the FS program comes up and take a screen shot but when saving to file ... that process does not work anymore and the notification does not come up anymore ... however when i copy to clipboard it works and gives me a notification and then i have to manually paste it into my file browser "dolphin" and give it a name ... i miss the automated save function for obvious reasons ... my PC is a Lenovo X1 running opensuse tumbleweed KDE 5 QT 5.

asking on GitHub is the last resort as i've tried everything else to get this to work.

Gracias

**Comment by sarg** [comment]
I had the same issue because of missing locale:
```
~ λ flameshot
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

Try running flameshot with `LANG=C flameshot` and then `flameshot gui`.

**Comment by qowai** [comment]
I've put the "LANG=C flameshot" into autostart ... and the print screen button calls up flameshot anyways ... so now it works again ... what a relief ... thank you very much!
