### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by samiurprapon** [lupoDharkael/flameshot#729]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.14.1
**Describe the bug**
Can not take screenshot

**To Reproduce**
➜  ~ flameshot
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

**Expected behavior**
Willing to take screenshot

**System Information**
OS: Manjaro Linux x86_64 
Kernel: 5.4.34-1-MANJARO

**Comment by tomatic** [comment]
Same on Kubuntu 19.10., crashes when clicking the save (to disk) icon after taking the screenshot. Weirdly, it doesn't crash if I launched it from a Konsole window. But if I launch it from Krunner, it crashes when I click the save button.

**Comment by str** [comment]
Same on ubuntu 20.04

**Comment by str** [comment]
Duplicated of #718

**Comment by dylskiMarcin** [comment]
For some reason std::locale::global(std::locale("")) is failing on KDE.
Putting it in try and catching runtime_error will make it use default c locale. 
This would fix this issue, but I didn't found in codebase other method of handling errors then popup windows. It would be at lest inconvenient to close window that says "Blah blah - switching to default locale" every time when you try to save screenshot. 

```
FileNameHandler::FileNameHandler(QObject *parent) : QObject(parent) {
    try{
        std::locale::global(std::locale(""));
    }catch(const std::runtime_error &e){

    }
}
```

**Comment by dylskiMarcin** [comment]
@tomatic @samiurprapon 
Solution that not require building application by yourself would be to uncheck "Detailed Settings" in System Settings->Regional Settings->Formats
[Formats setting screenshot](https://i.imgur.com/K6aGPm9.png)

**Comment by samiurprapon** [comment]
@dylskiMarcin Thanks buddy, it's now working smooth.
