### ISSUE TITLE
deleting from imgur?

### ISSUE THREAD

**Issue by nlegaillart** [lupoDharkael/flameshot#74]
Hi,

Is there a way to delete capture uploaded to imgur? is it uploaded using a particular account?

Regards,

**Comment by lupoDharkael** [comment]
Hello @nlegaillart.
Uploads are not associated with an account, thet are unauthenticated and based on an API key.
In order to delete an image you need the `deleteHash` returned by the HTTP response.

Actually the implementation of the imgur uploader doesn't save the deleteHash so I don't know if they can be deleted. I didn't think about the need to erase images when I wrote it.
I'll have to think how to implement a proper way to be able to delete them.

**Comment by nlegaillart** [comment]
ok, thanks a lot for the quick reply. and for your wonderful software :)

**Comment by burianvlastimil** [comment]
Is this ever going to work? (deleting from imgur)

**Comment by nkhi** [comment]
Was this ever sorted out? Just export the hash into a config file somewhere so this is at least manually possible

**Comment by whhone** [comment]
I think this "easy to upload but impossible to delete from Imgur" is a serious and irreversible privacy issue. e.g., A user could upload a screenshot containing personal data accidentally but have no way to delete it.

**Comment by borgmanJeremy** [comment]
I am completely reworking the image upload feature as part of our next release (0.9) Typing out the proposal now :)

**Comment by isrortega** [comment]
> I think this "easy to upload but impossible to delete from Imgur" is a serious and irreversible privacy issue. e.g., A user could upload a screenshot containing personal data accidentally but have no way to delete it.

I've already done it by mistake and I don't know how to remove it

**Comment by mmahmoudian** [comment]
@isrortega right click on the tray icon, then go to "Latest uploads", the find what you want to delete and delete it from there

**Comment by AzD3v** [comment]
@mmahmoudian, this option is not available on Ubuntu I assume? 

I'm using v20.04.

**Comment by mmahmoudian** [comment]
@AzD3v we are not affiliated with Ubuntu. This feature is in our latest Flameshot version. You can install the latest via Snap or Flatpak if you OS does not have the latest version

**Comment by AzD3v** [comment]
@mmahmoudian, I have the latest version.

Basically what happened was that I clicked on the upload icon by mistake, panicked and closed the upload loading window without knowing I would get the option to delete the image from Imgur afterwards. I'm almost sure the upload was still in progress but still, wanted to confirm.

Anyways, guess that's impossible now.

**Comment by mmahmoudian** [comment]
Sorry, there is nothing we can do, you can perhaps email the imgur and give them proper info (IP, time, ...) and ask them to delete it
