### ISSUE TITLE
Using invalid ui language name for Simplified Chinese (zh_CN) translation

### ISSUE THREAD

**Issue by hosiet** [lupoDharkael/flameshot#75]
Problem: Simplified Chinese translation not working.

Solution: rename `Internationalization_zh-cn.qm` to `Internationalization_zh_CN.qm`.

Reason: https://github.com/lupoDharkael/flameshot/blob/248c446dec64b36d3725b95703633867db94c344/src/main.cpp#L43

This is
```c++
bool QTranslator::load(const QLocale &locale, const QString &filename, const QString &prefix = QString(), const QString &directory = QString(), const QString &suffix = QString())
```
 which means
```Loads filename + prefix + ui language name + suffix (".qm" if the suffix is not specified)```.

However, `zh-cn` is not the valid "ui language name" for Simplified Chinese. It should be `zh_CN`.

Please fix this problem. (I'm too lazy to submit a PR for it this time :-p )

**Comment by lupoDharkael** [comment]
Your feedback is appreciated.
Hope this fixes the issue: https://github.com/lupoDharkael/flameshot/commit/dc50cd9193d00d06a99b5b2f8fb8463a70a50155

**Comment by hosiet** [comment]
Confirm fixed in latest git HEAD.
