### ISSUE TITLE
Text tool missing

### ISSUE THREAD

**Issue by Seybo** [lupoDharkael/flameshot#785]
**Flameshot version**
```
Flameshot v0.6.0
Compiled with Qt 5.9.5
```

**Describe the bug**
No text tool

**To Reproduce**
Download and install package `flameshot_0.6.0_bionic_x86_64.deb`

**Expected behavior**
Text tool presence

**System Information**
`Ubuntu 18.04.4 LTS`

**Comment by enricozb** [comment]
Have you tried `flameshot config` and making sure the text tool is selected? 

![image](https://user-images.githubusercontent.com/5505315/86538675-328d6100-beac-11ea-8945-a702b182b655.png)

**Comment by Seybo** [comment]
oh, sorry. I was sure i did check it but apparently i missed it. Thank you!

**Comment by luobizheng** [comment]
This option is set to off by default, which is very unfriendly

**Comment by craigstar** [comment]
I can not see this text option, don't know why. I've tried to compile source code and install with .deb. none of them have text option in config. I tried flameshot v0.6.0
my system is Ubuntu 18.04

**Comment by craigstar** [comment]
**installed with**: `flameshot_0.6.0_bionic_x86_64.deb`, **system**: `Ubuntu 18.04.5 LTS`. 
No Text Field in config. please help.
![image](https://user-images.githubusercontent.com/11722003/91948231-63660700-ed32-11ea-8122-7020ebf0fccc.png)

**Comment by CEHitchens** [comment]
Same issue as craigstar.
Linux Mint 19.3 Cinnamon; purged the former flameshot version, deleted Dharkael folder in /.config/, installed the latest *.deb and I don't see an option to enable the text input after I run "flameshot configure".
Yes, in LM20 this works.
