### ISSUE TITLE
MSVC build 

### ISSUE THREAD

**Issue by ZetaoYang** [lupoDharkael/flameshot#79]
To ensure that the project is compiled with MSVC build a set, should add the following lines to pro project file:
```
win32-msvc*{
    LIBS += -luser32
}
```

not `win32:LIBS += -luser32 `

Because under MinGw environment, compile normally.

more details: https://evileg.com/en/post/165/

**Comment by lupoDharkael** [comment]
LIBS is information for the linker. Liking against the actual defined libs is required in windows so I don't see why should the definition be restricted to a single compiler.
