### ISSUE TITLE
Settings GUI stop runing after unselect checkbox "show icon in system tray".

### ISSUE THREAD

**Issue by PetrJ-v** [lupoDharkael/flameshot#793]
**Flameshot version**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**System Information**

**Comment by PetrJ-v** [comment]
Program was installed with discover software center (System kubuntu 20.04).
Then checkbox hide icon in system tray is active, program gui doesn't start from application menu.
There is no way to remove the checkbox, since the graphical interface no longer starts and there is no way to get into the settings.
Reinstalling of program with discover doesn't help.

**Comment by PetrJ-v** [comment]
Any way, program is very cool. Thanks for this work!

**Comment by zhenglinli** [comment]
try command `flameshot config`?

**Comment by PetrJ-v** [comment]
This command work. Thank you for response . I close the issue.
I didn't see documentation. Now i readed it.
