### ISSUE TITLE
upload file to imgur

### ISSUE THREAD

**Issue by diniremix** [lupoDharkael/flameshot#8]
Thanks !, the application is just great.
I have compiled it in Fedora 23 and it works perfectly.
But when I try to make a capture and upload it to **imgur**, it says that it is uploading but does not show any notifications when it finishes uploading, or the url it generates from the image.

Sorry for the translation, I use Google Translate.

**Comment by lupoDharkael** [comment]
You need yo have an application defined in the system to open URLs (your browser for example), check that you have a program defined to open URLs in the "Prefered Applications" option in your desktop.
And it's true, I have to add some notification informing when things go wrong. 
Check your configurations and go back if the problem persists, I'll try to have a error notification message for the wrong upload for tomorrow.

**Comment by lupoDharkael** [comment]
I've pushed a new feature in the repo. Now if the upload goes wrong it should show why. Please, download and compile the code from the master branch (not from the last release) and let's see what happens if you keep having problems.

**Comment by diniremix** [comment]
I have downloaded the master branch and compiled, the result [here (pastebin)](https://pastebin.com/mFWmb1Dd), when I run it and I make the screenshot, the following error "**SSL handshake failed**"
A screenshot of the error message [here](http://imgur.com/a/mJcA4).
Thank you!.

**Comment by diniremix** [comment]
After reviewing a little in some [Qt forums,](http://www.qtcentre.org/threads/18762-QNetworkAccessManager-quot-SSL-handshake-failed-quot) the error was mine, because I'm behind a proxy and the imgur web was blocked, thank you, it already works correctly.

To finalize, it is possible that when the image is loaded to Imgur and the url is obtained, it can be copied to the clipboard.
Thank you very much for answering

**Comment by lupoDharkael** [comment]
Great!
Now I'm going to close the issue but I'll keep in mind about adding the option to copy the URL :)
