### ISSUE TITLE
Saving delay

### ISSUE THREAD

**Issue by vendforce** [lupoDharkael/flameshot#80]
OS : Arch
DE : Kde

flameshot version : 0.5.0

after editing the image and clicking save there is a long delay before the file is saved 10 or more secs 

why is there a delay in saving the file ?

**Comment by lupoDharkael** [comment]
I'll try to reproduce the issue in a virtual machine.

**Comment by vendforce** [comment]
I tested this on a laptop and theres no saving delay , when I tested it the last time I it was on my desktop with sli nvidia , I dont have any problems with my graphics other than this the desktop runs quick and no delay in framerate etc all other programs have no delay ??

**Comment by vendforce** [comment]
I retested it and its not freezing anymore , I got a few updates maybe some libararys need to be updated
