### ISSUE TITLE
The icon is hardcoded

### ISSUE THREAD

**Issue by GrayJack** [lupoDharkael/flameshot#91]
The applications .desktop file have the icon path hardcoded, would be better if not so if the icon theme have a flameshot icon so the icon become better blended with the system

**Comment by lupoDharkael** [comment]
The actual desktopfiles doesn't use hardcoded paths: https://github.com/lupoDharkael/flameshot/tree/master/docs/desktopEntry/package

**Comment by GrayJack** [comment]
Oh! it is hardcoded on the 0.5 version, I thought it wasn't fixed cause I didn't found the desktop files on the source tree, I never imagined that it would be on docs folder
