### ISSUE TITLE
System tray icon

### ISSUE THREAD

**Issue by shaygover** [lupoDharkael/flameshot#95]
Hi,

I see flameshot icon in my notification area instead of the system tray (KDE 5).
It means that every time I want to take a snapshot, I need to open the notification area. And it's annoying.

Can you move it to the system tray?

Thanks

**Comment by lupoDharkael** [comment]
I can't choose where it appears, you have to configure the components in your taskbars to make it show as you want.

Checkout here: https://github.com/lupoDharkael/flameshot#global
