### ISSUE TITLE
Increase visibility for selection crosshair

### ISSUE THREAD

**Issue by oyhel** [lupoDharkael/flameshot#99]
Thanks for a great app, this is hands down the quickest and most efficient tool to screen capture I've ever used! 

A tiny suggestion for enhancement, though; I am using Redshift to lower bluelight in KDE. When the screen is tinted it is very hard/impossible to see the crosshair for selection. I usually draw a quick rectangle just to identify the cursor, and then do the intended selection. If it was possible to change the color/thickness of the crosshair that would be great.

**Comment by lupoDharkael** [comment]
I'm glad you are having a good experience!
I'm closing this as there is one issue open about this, check my response there: https://github.com/lupoDharkael/flameshot/issues/82

**Comment by oyhel** [comment]
I am sorry, my quick glance through the reported issues did not catch this! Thanks again!
